// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package pl.wroc.pwr.wiz.io.psi.model;

import pl.wroc.pwr.wiz.io.psi.model.Kraj;

privileged aspect Kraj_Roo_JavaBean {
    
    public String Kraj.getNazwa() {
        return this.nazwa;
    }
    
    public void Kraj.setNazwa(String nazwa) {
        this.nazwa = nazwa;
    }
    
}
