// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package pl.wroc.pwr.wiz.io.psi.model;

import pl.wroc.pwr.wiz.io.psi.model.Powiadomienie;

privileged aspect Powiadomienie_Roo_JavaBean {
    
    public String Powiadomienie.getTresc() {
        return this.tresc;
    }
    
    public void Powiadomienie.setTresc(String tresc) {
        this.tresc = tresc;
    }
    
}
