// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package pl.wroc.pwr.wiz.io.psi.model;

import org.springframework.beans.factory.annotation.Configurable;
import pl.wroc.pwr.wiz.io.psi.model.SubskrypcjaUlubionejKategorii;

privileged aspect SubskrypcjaUlubionejKategorii_Roo_Configurable {
    
    declare @type: SubskrypcjaUlubionejKategorii: @Configurable;
    
}
