// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package pl.wroc.pwr.wiz.io.psi.model;

import pl.wroc.pwr.wiz.io.psi.model.Zdjecie;

privileged aspect Zdjecie_Roo_JavaBean {
    
    public String Zdjecie.getOpis() {
        return this.opis;
    }
    
    public void Zdjecie.setOpis(String opis) {
        this.opis = opis;
    }
    
}
