// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package pl.wroc.pwr.wiz.io.psi.model;

import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;
import pl.wroc.pwr.wiz.io.psi.model.CennikDostaw;
import pl.wroc.pwr.wiz.io.psi.model.CennikDostawDataOnDemand;
import pl.wroc.pwr.wiz.io.psi.model.CennikDostawIntegrationTest;

privileged aspect CennikDostawIntegrationTest_Roo_IntegrationTest {
    
    declare @type: CennikDostawIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: CennikDostawIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: CennikDostawIntegrationTest: @Transactional;
    
    @Autowired
    CennikDostawDataOnDemand CennikDostawIntegrationTest.dod;
    
    @Test
    public void CennikDostawIntegrationTest.testCountCennikDostaws() {
        Assert.assertNotNull("Data on demand for 'CennikDostaw' failed to initialize correctly", dod.getRandomCennikDostaw());
        long count = CennikDostaw.countCennikDostaws();
        Assert.assertTrue("Counter for 'CennikDostaw' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void CennikDostawIntegrationTest.testFindCennikDostaw() {
        CennikDostaw obj = dod.getRandomCennikDostaw();
        Assert.assertNotNull("Data on demand for 'CennikDostaw' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'CennikDostaw' failed to provide an identifier", id);
        obj = CennikDostaw.findCennikDostaw(id);
        Assert.assertNotNull("Find method for 'CennikDostaw' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'CennikDostaw' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void CennikDostawIntegrationTest.testFindAllCennikDostaws() {
        Assert.assertNotNull("Data on demand for 'CennikDostaw' failed to initialize correctly", dod.getRandomCennikDostaw());
        long count = CennikDostaw.countCennikDostaws();
        Assert.assertTrue("Too expensive to perform a find all test for 'CennikDostaw', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<CennikDostaw> result = CennikDostaw.findAllCennikDostaws();
        Assert.assertNotNull("Find all method for 'CennikDostaw' illegally returned null", result);
        Assert.assertTrue("Find all method for 'CennikDostaw' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void CennikDostawIntegrationTest.testFindCennikDostawEntries() {
        Assert.assertNotNull("Data on demand for 'CennikDostaw' failed to initialize correctly", dod.getRandomCennikDostaw());
        long count = CennikDostaw.countCennikDostaws();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<CennikDostaw> result = CennikDostaw.findCennikDostawEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'CennikDostaw' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'CennikDostaw' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void CennikDostawIntegrationTest.testFlush() {
        CennikDostaw obj = dod.getRandomCennikDostaw();
        Assert.assertNotNull("Data on demand for 'CennikDostaw' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'CennikDostaw' failed to provide an identifier", id);
        obj = CennikDostaw.findCennikDostaw(id);
        Assert.assertNotNull("Find method for 'CennikDostaw' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyCennikDostaw(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'CennikDostaw' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void CennikDostawIntegrationTest.testMergeUpdate() {
        CennikDostaw obj = dod.getRandomCennikDostaw();
        Assert.assertNotNull("Data on demand for 'CennikDostaw' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'CennikDostaw' failed to provide an identifier", id);
        obj = CennikDostaw.findCennikDostaw(id);
        boolean modified =  dod.modifyCennikDostaw(obj);
        Integer currentVersion = obj.getVersion();
        CennikDostaw merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'CennikDostaw' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void CennikDostawIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'CennikDostaw' failed to initialize correctly", dod.getRandomCennikDostaw());
        CennikDostaw obj = dod.getNewTransientCennikDostaw(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'CennikDostaw' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'CennikDostaw' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'CennikDostaw' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void CennikDostawIntegrationTest.testRemove() {
        CennikDostaw obj = dod.getRandomCennikDostaw();
        Assert.assertNotNull("Data on demand for 'CennikDostaw' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'CennikDostaw' failed to provide an identifier", id);
        obj = CennikDostaw.findCennikDostaw(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'CennikDostaw' with identifier '" + id + "'", CennikDostaw.findCennikDostaw(id));
    }
    
}
