// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package pl.wroc.pwr.wiz.io.psi.model;

import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;
import pl.wroc.pwr.wiz.io.psi.model.DaneDoWysylki;
import pl.wroc.pwr.wiz.io.psi.model.DaneDoWysylkiDataOnDemand;
import pl.wroc.pwr.wiz.io.psi.model.DaneDoWysylkiIntegrationTest;

privileged aspect DaneDoWysylkiIntegrationTest_Roo_IntegrationTest {
    
    declare @type: DaneDoWysylkiIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: DaneDoWysylkiIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: DaneDoWysylkiIntegrationTest: @Transactional;
    
    @Autowired
    DaneDoWysylkiDataOnDemand DaneDoWysylkiIntegrationTest.dod;
    
    @Test
    public void DaneDoWysylkiIntegrationTest.testCountDaneDoWysylkis() {
        Assert.assertNotNull("Data on demand for 'DaneDoWysylki' failed to initialize correctly", dod.getRandomDaneDoWysylki());
        long count = DaneDoWysylki.countDaneDoWysylkis();
        Assert.assertTrue("Counter for 'DaneDoWysylki' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void DaneDoWysylkiIntegrationTest.testFindDaneDoWysylki() {
        DaneDoWysylki obj = dod.getRandomDaneDoWysylki();
        Assert.assertNotNull("Data on demand for 'DaneDoWysylki' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'DaneDoWysylki' failed to provide an identifier", id);
        obj = DaneDoWysylki.findDaneDoWysylki(id);
        Assert.assertNotNull("Find method for 'DaneDoWysylki' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'DaneDoWysylki' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void DaneDoWysylkiIntegrationTest.testFindAllDaneDoWysylkis() {
        Assert.assertNotNull("Data on demand for 'DaneDoWysylki' failed to initialize correctly", dod.getRandomDaneDoWysylki());
        long count = DaneDoWysylki.countDaneDoWysylkis();
        Assert.assertTrue("Too expensive to perform a find all test for 'DaneDoWysylki', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<DaneDoWysylki> result = DaneDoWysylki.findAllDaneDoWysylkis();
        Assert.assertNotNull("Find all method for 'DaneDoWysylki' illegally returned null", result);
        Assert.assertTrue("Find all method for 'DaneDoWysylki' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void DaneDoWysylkiIntegrationTest.testFindDaneDoWysylkiEntries() {
        Assert.assertNotNull("Data on demand for 'DaneDoWysylki' failed to initialize correctly", dod.getRandomDaneDoWysylki());
        long count = DaneDoWysylki.countDaneDoWysylkis();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<DaneDoWysylki> result = DaneDoWysylki.findDaneDoWysylkiEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'DaneDoWysylki' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'DaneDoWysylki' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void DaneDoWysylkiIntegrationTest.testFlush() {
        DaneDoWysylki obj = dod.getRandomDaneDoWysylki();
        Assert.assertNotNull("Data on demand for 'DaneDoWysylki' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'DaneDoWysylki' failed to provide an identifier", id);
        obj = DaneDoWysylki.findDaneDoWysylki(id);
        Assert.assertNotNull("Find method for 'DaneDoWysylki' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyDaneDoWysylki(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'DaneDoWysylki' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void DaneDoWysylkiIntegrationTest.testMergeUpdate() {
        DaneDoWysylki obj = dod.getRandomDaneDoWysylki();
        Assert.assertNotNull("Data on demand for 'DaneDoWysylki' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'DaneDoWysylki' failed to provide an identifier", id);
        obj = DaneDoWysylki.findDaneDoWysylki(id);
        boolean modified =  dod.modifyDaneDoWysylki(obj);
        Integer currentVersion = obj.getVersion();
        DaneDoWysylki merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'DaneDoWysylki' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void DaneDoWysylkiIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'DaneDoWysylki' failed to initialize correctly", dod.getRandomDaneDoWysylki());
        DaneDoWysylki obj = dod.getNewTransientDaneDoWysylki(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'DaneDoWysylki' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'DaneDoWysylki' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'DaneDoWysylki' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void DaneDoWysylkiIntegrationTest.testRemove() {
        DaneDoWysylki obj = dod.getRandomDaneDoWysylki();
        Assert.assertNotNull("Data on demand for 'DaneDoWysylki' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'DaneDoWysylki' failed to provide an identifier", id);
        obj = DaneDoWysylki.findDaneDoWysylki(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'DaneDoWysylki' with identifier '" + id + "'", DaneDoWysylki.findDaneDoWysylki(id));
    }
    
}
