// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package pl.wroc.pwr.wiz.io.psi.model;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;
import pl.wroc.pwr.wiz.io.psi.model.DaneDoWysylki;
import pl.wroc.pwr.wiz.io.psi.model.DaneDoWysylkiDataOnDemand;

privileged aspect DaneDoWysylkiDataOnDemand_Roo_DataOnDemand {
    
    declare @type: DaneDoWysylkiDataOnDemand: @Component;
    
    private Random DaneDoWysylkiDataOnDemand.rnd = new SecureRandom();
    
    private List<DaneDoWysylki> DaneDoWysylkiDataOnDemand.data;
    
    public DaneDoWysylki DaneDoWysylkiDataOnDemand.getNewTransientDaneDoWysylki(int index) {
        DaneDoWysylki obj = new DaneDoWysylki();
        setFirma(obj, index);
        setImie(obj, index);
        setNazwisko(obj, index);
        return obj;
    }
    
    public void DaneDoWysylkiDataOnDemand.setFirma(DaneDoWysylki obj, int index) {
        String firma = "firma_" + index;
        obj.setFirma(firma);
    }
    
    public void DaneDoWysylkiDataOnDemand.setImie(DaneDoWysylki obj, int index) {
        String imie = "imie_" + index;
        obj.setImie(imie);
    }
    
    public void DaneDoWysylkiDataOnDemand.setNazwisko(DaneDoWysylki obj, int index) {
        String nazwisko = "nazwisko_" + index;
        obj.setNazwisko(nazwisko);
    }
    
    public DaneDoWysylki DaneDoWysylkiDataOnDemand.getSpecificDaneDoWysylki(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        DaneDoWysylki obj = data.get(index);
        Long id = obj.getId();
        return DaneDoWysylki.findDaneDoWysylki(id);
    }
    
    public DaneDoWysylki DaneDoWysylkiDataOnDemand.getRandomDaneDoWysylki() {
        init();
        DaneDoWysylki obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return DaneDoWysylki.findDaneDoWysylki(id);
    }
    
    public boolean DaneDoWysylkiDataOnDemand.modifyDaneDoWysylki(DaneDoWysylki obj) {
        return false;
    }
    
    public void DaneDoWysylkiDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = DaneDoWysylki.findDaneDoWysylkiEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'DaneDoWysylki' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<DaneDoWysylki>();
        for (int i = 0; i < 10; i++) {
            DaneDoWysylki obj = getNewTransientDaneDoWysylki(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
