// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package pl.wroc.pwr.wiz.io.psi.model;

import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;
import pl.wroc.pwr.wiz.io.psi.model.GraficznaOcenaSprzedazy;
import pl.wroc.pwr.wiz.io.psi.model.GraficznaOcenaSprzedazyDataOnDemand;
import pl.wroc.pwr.wiz.io.psi.model.GraficznaOcenaSprzedazyIntegrationTest;

privileged aspect GraficznaOcenaSprzedazyIntegrationTest_Roo_IntegrationTest {
    
    declare @type: GraficznaOcenaSprzedazyIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: GraficznaOcenaSprzedazyIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: GraficznaOcenaSprzedazyIntegrationTest: @Transactional;
    
    @Autowired
    GraficznaOcenaSprzedazyDataOnDemand GraficznaOcenaSprzedazyIntegrationTest.dod;
    
    @Test
    public void GraficznaOcenaSprzedazyIntegrationTest.testCountGraficznaOcenaSprzedazys() {
        Assert.assertNotNull("Data on demand for 'GraficznaOcenaSprzedazy' failed to initialize correctly", dod.getRandomGraficznaOcenaSprzedazy());
        long count = GraficznaOcenaSprzedazy.countGraficznaOcenaSprzedazys();
        Assert.assertTrue("Counter for 'GraficznaOcenaSprzedazy' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void GraficznaOcenaSprzedazyIntegrationTest.testFindGraficznaOcenaSprzedazy() {
        GraficznaOcenaSprzedazy obj = dod.getRandomGraficznaOcenaSprzedazy();
        Assert.assertNotNull("Data on demand for 'GraficznaOcenaSprzedazy' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'GraficznaOcenaSprzedazy' failed to provide an identifier", id);
        obj = GraficznaOcenaSprzedazy.findGraficznaOcenaSprzedazy(id);
        Assert.assertNotNull("Find method for 'GraficznaOcenaSprzedazy' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'GraficznaOcenaSprzedazy' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void GraficznaOcenaSprzedazyIntegrationTest.testFindAllGraficznaOcenaSprzedazys() {
        Assert.assertNotNull("Data on demand for 'GraficznaOcenaSprzedazy' failed to initialize correctly", dod.getRandomGraficznaOcenaSprzedazy());
        long count = GraficznaOcenaSprzedazy.countGraficznaOcenaSprzedazys();
        Assert.assertTrue("Too expensive to perform a find all test for 'GraficznaOcenaSprzedazy', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<GraficznaOcenaSprzedazy> result = GraficznaOcenaSprzedazy.findAllGraficznaOcenaSprzedazys();
        Assert.assertNotNull("Find all method for 'GraficznaOcenaSprzedazy' illegally returned null", result);
        Assert.assertTrue("Find all method for 'GraficznaOcenaSprzedazy' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void GraficznaOcenaSprzedazyIntegrationTest.testFindGraficznaOcenaSprzedazyEntries() {
        Assert.assertNotNull("Data on demand for 'GraficznaOcenaSprzedazy' failed to initialize correctly", dod.getRandomGraficznaOcenaSprzedazy());
        long count = GraficznaOcenaSprzedazy.countGraficznaOcenaSprzedazys();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<GraficznaOcenaSprzedazy> result = GraficznaOcenaSprzedazy.findGraficznaOcenaSprzedazyEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'GraficznaOcenaSprzedazy' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'GraficznaOcenaSprzedazy' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void GraficznaOcenaSprzedazyIntegrationTest.testFlush() {
        GraficznaOcenaSprzedazy obj = dod.getRandomGraficznaOcenaSprzedazy();
        Assert.assertNotNull("Data on demand for 'GraficznaOcenaSprzedazy' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'GraficznaOcenaSprzedazy' failed to provide an identifier", id);
        obj = GraficznaOcenaSprzedazy.findGraficznaOcenaSprzedazy(id);
        Assert.assertNotNull("Find method for 'GraficznaOcenaSprzedazy' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyGraficznaOcenaSprzedazy(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'GraficznaOcenaSprzedazy' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void GraficznaOcenaSprzedazyIntegrationTest.testMergeUpdate() {
        GraficznaOcenaSprzedazy obj = dod.getRandomGraficznaOcenaSprzedazy();
        Assert.assertNotNull("Data on demand for 'GraficznaOcenaSprzedazy' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'GraficznaOcenaSprzedazy' failed to provide an identifier", id);
        obj = GraficznaOcenaSprzedazy.findGraficznaOcenaSprzedazy(id);
        boolean modified =  dod.modifyGraficznaOcenaSprzedazy(obj);
        Integer currentVersion = obj.getVersion();
        GraficznaOcenaSprzedazy merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'GraficznaOcenaSprzedazy' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void GraficznaOcenaSprzedazyIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'GraficznaOcenaSprzedazy' failed to initialize correctly", dod.getRandomGraficznaOcenaSprzedazy());
        GraficznaOcenaSprzedazy obj = dod.getNewTransientGraficznaOcenaSprzedazy(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'GraficznaOcenaSprzedazy' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'GraficznaOcenaSprzedazy' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'GraficznaOcenaSprzedazy' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void GraficznaOcenaSprzedazyIntegrationTest.testRemove() {
        GraficznaOcenaSprzedazy obj = dod.getRandomGraficznaOcenaSprzedazy();
        Assert.assertNotNull("Data on demand for 'GraficznaOcenaSprzedazy' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'GraficznaOcenaSprzedazy' failed to provide an identifier", id);
        obj = GraficznaOcenaSprzedazy.findGraficznaOcenaSprzedazy(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'GraficznaOcenaSprzedazy' with identifier '" + id + "'", GraficznaOcenaSprzedazy.findGraficznaOcenaSprzedazy(id));
    }
    
}
