// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package pl.wroc.pwr.wiz.io.psi.model;

import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;
import pl.wroc.pwr.wiz.io.psi.model.HistoriaZmianOpisu;
import pl.wroc.pwr.wiz.io.psi.model.HistoriaZmianOpisuDataOnDemand;
import pl.wroc.pwr.wiz.io.psi.model.HistoriaZmianOpisuIntegrationTest;

privileged aspect HistoriaZmianOpisuIntegrationTest_Roo_IntegrationTest {
    
    declare @type: HistoriaZmianOpisuIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: HistoriaZmianOpisuIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: HistoriaZmianOpisuIntegrationTest: @Transactional;
    
    @Autowired
    HistoriaZmianOpisuDataOnDemand HistoriaZmianOpisuIntegrationTest.dod;
    
    @Test
    public void HistoriaZmianOpisuIntegrationTest.testCountHistoriaZmianOpisus() {
        Assert.assertNotNull("Data on demand for 'HistoriaZmianOpisu' failed to initialize correctly", dod.getRandomHistoriaZmianOpisu());
        long count = HistoriaZmianOpisu.countHistoriaZmianOpisus();
        Assert.assertTrue("Counter for 'HistoriaZmianOpisu' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void HistoriaZmianOpisuIntegrationTest.testFindHistoriaZmianOpisu() {
        HistoriaZmianOpisu obj = dod.getRandomHistoriaZmianOpisu();
        Assert.assertNotNull("Data on demand for 'HistoriaZmianOpisu' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'HistoriaZmianOpisu' failed to provide an identifier", id);
        obj = HistoriaZmianOpisu.findHistoriaZmianOpisu(id);
        Assert.assertNotNull("Find method for 'HistoriaZmianOpisu' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'HistoriaZmianOpisu' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void HistoriaZmianOpisuIntegrationTest.testFindAllHistoriaZmianOpisus() {
        Assert.assertNotNull("Data on demand for 'HistoriaZmianOpisu' failed to initialize correctly", dod.getRandomHistoriaZmianOpisu());
        long count = HistoriaZmianOpisu.countHistoriaZmianOpisus();
        Assert.assertTrue("Too expensive to perform a find all test for 'HistoriaZmianOpisu', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<HistoriaZmianOpisu> result = HistoriaZmianOpisu.findAllHistoriaZmianOpisus();
        Assert.assertNotNull("Find all method for 'HistoriaZmianOpisu' illegally returned null", result);
        Assert.assertTrue("Find all method for 'HistoriaZmianOpisu' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void HistoriaZmianOpisuIntegrationTest.testFindHistoriaZmianOpisuEntries() {
        Assert.assertNotNull("Data on demand for 'HistoriaZmianOpisu' failed to initialize correctly", dod.getRandomHistoriaZmianOpisu());
        long count = HistoriaZmianOpisu.countHistoriaZmianOpisus();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<HistoriaZmianOpisu> result = HistoriaZmianOpisu.findHistoriaZmianOpisuEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'HistoriaZmianOpisu' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'HistoriaZmianOpisu' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void HistoriaZmianOpisuIntegrationTest.testFlush() {
        HistoriaZmianOpisu obj = dod.getRandomHistoriaZmianOpisu();
        Assert.assertNotNull("Data on demand for 'HistoriaZmianOpisu' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'HistoriaZmianOpisu' failed to provide an identifier", id);
        obj = HistoriaZmianOpisu.findHistoriaZmianOpisu(id);
        Assert.assertNotNull("Find method for 'HistoriaZmianOpisu' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyHistoriaZmianOpisu(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'HistoriaZmianOpisu' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void HistoriaZmianOpisuIntegrationTest.testMergeUpdate() {
        HistoriaZmianOpisu obj = dod.getRandomHistoriaZmianOpisu();
        Assert.assertNotNull("Data on demand for 'HistoriaZmianOpisu' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'HistoriaZmianOpisu' failed to provide an identifier", id);
        obj = HistoriaZmianOpisu.findHistoriaZmianOpisu(id);
        boolean modified =  dod.modifyHistoriaZmianOpisu(obj);
        Integer currentVersion = obj.getVersion();
        HistoriaZmianOpisu merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'HistoriaZmianOpisu' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void HistoriaZmianOpisuIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'HistoriaZmianOpisu' failed to initialize correctly", dod.getRandomHistoriaZmianOpisu());
        HistoriaZmianOpisu obj = dod.getNewTransientHistoriaZmianOpisu(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'HistoriaZmianOpisu' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'HistoriaZmianOpisu' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'HistoriaZmianOpisu' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void HistoriaZmianOpisuIntegrationTest.testRemove() {
        HistoriaZmianOpisu obj = dod.getRandomHistoriaZmianOpisu();
        Assert.assertNotNull("Data on demand for 'HistoriaZmianOpisu' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'HistoriaZmianOpisu' failed to provide an identifier", id);
        obj = HistoriaZmianOpisu.findHistoriaZmianOpisu(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'HistoriaZmianOpisu' with identifier '" + id + "'", HistoriaZmianOpisu.findHistoriaZmianOpisu(id));
    }
    
}
