// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package pl.wroc.pwr.wiz.io.psi.model;

import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;
import pl.wroc.pwr.wiz.io.psi.model.Kategoria;
import pl.wroc.pwr.wiz.io.psi.model.KategoriaDataOnDemand;
import pl.wroc.pwr.wiz.io.psi.model.KategoriaIntegrationTest;

privileged aspect KategoriaIntegrationTest_Roo_IntegrationTest {
    
    declare @type: KategoriaIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: KategoriaIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: KategoriaIntegrationTest: @Transactional;
    
    @Autowired
    KategoriaDataOnDemand KategoriaIntegrationTest.dod;
    
    @Test
    public void KategoriaIntegrationTest.testCountKategorias() {
        Assert.assertNotNull("Data on demand for 'Kategoria' failed to initialize correctly", dod.getRandomKategoria());
        long count = Kategoria.countKategorias();
        Assert.assertTrue("Counter for 'Kategoria' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void KategoriaIntegrationTest.testFindKategoria() {
        Kategoria obj = dod.getRandomKategoria();
        Assert.assertNotNull("Data on demand for 'Kategoria' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Kategoria' failed to provide an identifier", id);
        obj = Kategoria.findKategoria(id);
        Assert.assertNotNull("Find method for 'Kategoria' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Kategoria' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void KategoriaIntegrationTest.testFindAllKategorias() {
        Assert.assertNotNull("Data on demand for 'Kategoria' failed to initialize correctly", dod.getRandomKategoria());
        long count = Kategoria.countKategorias();
        Assert.assertTrue("Too expensive to perform a find all test for 'Kategoria', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Kategoria> result = Kategoria.findAllKategorias();
        Assert.assertNotNull("Find all method for 'Kategoria' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Kategoria' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void KategoriaIntegrationTest.testFindKategoriaEntries() {
        Assert.assertNotNull("Data on demand for 'Kategoria' failed to initialize correctly", dod.getRandomKategoria());
        long count = Kategoria.countKategorias();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Kategoria> result = Kategoria.findKategoriaEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Kategoria' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Kategoria' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void KategoriaIntegrationTest.testFlush() {
        Kategoria obj = dod.getRandomKategoria();
        Assert.assertNotNull("Data on demand for 'Kategoria' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Kategoria' failed to provide an identifier", id);
        obj = Kategoria.findKategoria(id);
        Assert.assertNotNull("Find method for 'Kategoria' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyKategoria(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Kategoria' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void KategoriaIntegrationTest.testMergeUpdate() {
        Kategoria obj = dod.getRandomKategoria();
        Assert.assertNotNull("Data on demand for 'Kategoria' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Kategoria' failed to provide an identifier", id);
        obj = Kategoria.findKategoria(id);
        boolean modified =  dod.modifyKategoria(obj);
        Integer currentVersion = obj.getVersion();
        Kategoria merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Kategoria' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void KategoriaIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Kategoria' failed to initialize correctly", dod.getRandomKategoria());
        Kategoria obj = dod.getNewTransientKategoria(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Kategoria' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Kategoria' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Kategoria' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void KategoriaIntegrationTest.testRemove() {
        Kategoria obj = dod.getRandomKategoria();
        Assert.assertNotNull("Data on demand for 'Kategoria' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Kategoria' failed to provide an identifier", id);
        obj = Kategoria.findKategoria(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Kategoria' with identifier '" + id + "'", Kategoria.findKategoria(id));
    }
    
}
