// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package pl.wroc.pwr.wiz.io.psi.model;

import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;
import pl.wroc.pwr.wiz.io.psi.model.Kraj;
import pl.wroc.pwr.wiz.io.psi.model.KrajDataOnDemand;
import pl.wroc.pwr.wiz.io.psi.model.KrajIntegrationTest;

privileged aspect KrajIntegrationTest_Roo_IntegrationTest {
    
    declare @type: KrajIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: KrajIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: KrajIntegrationTest: @Transactional;
    
    @Autowired
    KrajDataOnDemand KrajIntegrationTest.dod;
    
    @Test
    public void KrajIntegrationTest.testCountKrajs() {
        Assert.assertNotNull("Data on demand for 'Kraj' failed to initialize correctly", dod.getRandomKraj());
        long count = Kraj.countKrajs();
        Assert.assertTrue("Counter for 'Kraj' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void KrajIntegrationTest.testFindKraj() {
        Kraj obj = dod.getRandomKraj();
        Assert.assertNotNull("Data on demand for 'Kraj' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Kraj' failed to provide an identifier", id);
        obj = Kraj.findKraj(id);
        Assert.assertNotNull("Find method for 'Kraj' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Kraj' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void KrajIntegrationTest.testFindAllKrajs() {
        Assert.assertNotNull("Data on demand for 'Kraj' failed to initialize correctly", dod.getRandomKraj());
        long count = Kraj.countKrajs();
        Assert.assertTrue("Too expensive to perform a find all test for 'Kraj', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Kraj> result = Kraj.findAllKrajs();
        Assert.assertNotNull("Find all method for 'Kraj' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Kraj' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void KrajIntegrationTest.testFindKrajEntries() {
        Assert.assertNotNull("Data on demand for 'Kraj' failed to initialize correctly", dod.getRandomKraj());
        long count = Kraj.countKrajs();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Kraj> result = Kraj.findKrajEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Kraj' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Kraj' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void KrajIntegrationTest.testFlush() {
        Kraj obj = dod.getRandomKraj();
        Assert.assertNotNull("Data on demand for 'Kraj' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Kraj' failed to provide an identifier", id);
        obj = Kraj.findKraj(id);
        Assert.assertNotNull("Find method for 'Kraj' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyKraj(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Kraj' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void KrajIntegrationTest.testMergeUpdate() {
        Kraj obj = dod.getRandomKraj();
        Assert.assertNotNull("Data on demand for 'Kraj' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Kraj' failed to provide an identifier", id);
        obj = Kraj.findKraj(id);
        boolean modified =  dod.modifyKraj(obj);
        Integer currentVersion = obj.getVersion();
        Kraj merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Kraj' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void KrajIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Kraj' failed to initialize correctly", dod.getRandomKraj());
        Kraj obj = dod.getNewTransientKraj(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Kraj' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Kraj' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Kraj' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void KrajIntegrationTest.testRemove() {
        Kraj obj = dod.getRandomKraj();
        Assert.assertNotNull("Data on demand for 'Kraj' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Kraj' failed to provide an identifier", id);
        obj = Kraj.findKraj(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Kraj' with identifier '" + id + "'", Kraj.findKraj(id));
    }
    
}
