// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package pl.wroc.pwr.wiz.io.psi.model;

import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;
import pl.wroc.pwr.wiz.io.psi.model.ListAktywacyjny;
import pl.wroc.pwr.wiz.io.psi.model.ListAktywacyjnyDataOnDemand;
import pl.wroc.pwr.wiz.io.psi.model.ListAktywacyjnyIntegrationTest;

privileged aspect ListAktywacyjnyIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ListAktywacyjnyIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ListAktywacyjnyIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: ListAktywacyjnyIntegrationTest: @Transactional;
    
    @Autowired
    ListAktywacyjnyDataOnDemand ListAktywacyjnyIntegrationTest.dod;
    
    @Test
    public void ListAktywacyjnyIntegrationTest.testCountListAktywacyjnys() {
        Assert.assertNotNull("Data on demand for 'ListAktywacyjny' failed to initialize correctly", dod.getRandomListAktywacyjny());
        long count = ListAktywacyjny.countListAktywacyjnys();
        Assert.assertTrue("Counter for 'ListAktywacyjny' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ListAktywacyjnyIntegrationTest.testFindListAktywacyjny() {
        ListAktywacyjny obj = dod.getRandomListAktywacyjny();
        Assert.assertNotNull("Data on demand for 'ListAktywacyjny' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ListAktywacyjny' failed to provide an identifier", id);
        obj = ListAktywacyjny.findListAktywacyjny(id);
        Assert.assertNotNull("Find method for 'ListAktywacyjny' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'ListAktywacyjny' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ListAktywacyjnyIntegrationTest.testFindAllListAktywacyjnys() {
        Assert.assertNotNull("Data on demand for 'ListAktywacyjny' failed to initialize correctly", dod.getRandomListAktywacyjny());
        long count = ListAktywacyjny.countListAktywacyjnys();
        Assert.assertTrue("Too expensive to perform a find all test for 'ListAktywacyjny', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<ListAktywacyjny> result = ListAktywacyjny.findAllListAktywacyjnys();
        Assert.assertNotNull("Find all method for 'ListAktywacyjny' illegally returned null", result);
        Assert.assertTrue("Find all method for 'ListAktywacyjny' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ListAktywacyjnyIntegrationTest.testFindListAktywacyjnyEntries() {
        Assert.assertNotNull("Data on demand for 'ListAktywacyjny' failed to initialize correctly", dod.getRandomListAktywacyjny());
        long count = ListAktywacyjny.countListAktywacyjnys();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<ListAktywacyjny> result = ListAktywacyjny.findListAktywacyjnyEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'ListAktywacyjny' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'ListAktywacyjny' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ListAktywacyjnyIntegrationTest.testFlush() {
        ListAktywacyjny obj = dod.getRandomListAktywacyjny();
        Assert.assertNotNull("Data on demand for 'ListAktywacyjny' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ListAktywacyjny' failed to provide an identifier", id);
        obj = ListAktywacyjny.findListAktywacyjny(id);
        Assert.assertNotNull("Find method for 'ListAktywacyjny' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyListAktywacyjny(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'ListAktywacyjny' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ListAktywacyjnyIntegrationTest.testMergeUpdate() {
        ListAktywacyjny obj = dod.getRandomListAktywacyjny();
        Assert.assertNotNull("Data on demand for 'ListAktywacyjny' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ListAktywacyjny' failed to provide an identifier", id);
        obj = ListAktywacyjny.findListAktywacyjny(id);
        boolean modified =  dod.modifyListAktywacyjny(obj);
        Integer currentVersion = obj.getVersion();
        ListAktywacyjny merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'ListAktywacyjny' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ListAktywacyjnyIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'ListAktywacyjny' failed to initialize correctly", dod.getRandomListAktywacyjny());
        ListAktywacyjny obj = dod.getNewTransientListAktywacyjny(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'ListAktywacyjny' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'ListAktywacyjny' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'ListAktywacyjny' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ListAktywacyjnyIntegrationTest.testRemove() {
        ListAktywacyjny obj = dod.getRandomListAktywacyjny();
        Assert.assertNotNull("Data on demand for 'ListAktywacyjny' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ListAktywacyjny' failed to provide an identifier", id);
        obj = ListAktywacyjny.findListAktywacyjny(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'ListAktywacyjny' with identifier '" + id + "'", ListAktywacyjny.findListAktywacyjny(id));
    }
    
}
