// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package pl.wroc.pwr.wiz.io.psi.model;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import pl.wroc.pwr.wiz.io.psi.model.ListAktywacyjny;
import pl.wroc.pwr.wiz.io.psi.model.ListAktywacyjnyDataOnDemand;
import pl.wroc.pwr.wiz.io.psi.model.UczestnikDataOnDemand;

privileged aspect ListAktywacyjnyDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ListAktywacyjnyDataOnDemand: @Component;
    
    private Random ListAktywacyjnyDataOnDemand.rnd = new SecureRandom();
    
    private List<ListAktywacyjny> ListAktywacyjnyDataOnDemand.data;
    
    @Autowired
    UczestnikDataOnDemand ListAktywacyjnyDataOnDemand.uczestnikDataOnDemand;
    
    public ListAktywacyjny ListAktywacyjnyDataOnDemand.getNewTransientListAktywacyjny(int index) {
        ListAktywacyjny obj = new ListAktywacyjny();
        setDataWyslania(obj, index);
        setDataZamowienia(obj, index);
        setKodAktywacyjny(obj, index);
        setWpisanyPoprawnie(obj, index);
        return obj;
    }
    
    public void ListAktywacyjnyDataOnDemand.setDataWyslania(ListAktywacyjny obj, int index) {
        Date dataWyslania = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setDataWyslania(dataWyslania);
    }
    
    public void ListAktywacyjnyDataOnDemand.setDataZamowienia(ListAktywacyjny obj, int index) {
        Date dataZamowienia = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setDataZamowienia(dataZamowienia);
    }
    
    public void ListAktywacyjnyDataOnDemand.setKodAktywacyjny(ListAktywacyjny obj, int index) {
        int kodAktywacyjny = index;
        obj.setKodAktywacyjny(kodAktywacyjny);
    }
    
    public void ListAktywacyjnyDataOnDemand.setWpisanyPoprawnie(ListAktywacyjny obj, int index) {
        Boolean wpisanyPoprawnie = Boolean.TRUE;
        obj.setWpisanyPoprawnie(wpisanyPoprawnie);
    }
    
    public ListAktywacyjny ListAktywacyjnyDataOnDemand.getSpecificListAktywacyjny(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        ListAktywacyjny obj = data.get(index);
        Long id = obj.getId();
        return ListAktywacyjny.findListAktywacyjny(id);
    }
    
    public ListAktywacyjny ListAktywacyjnyDataOnDemand.getRandomListAktywacyjny() {
        init();
        ListAktywacyjny obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return ListAktywacyjny.findListAktywacyjny(id);
    }
    
    public boolean ListAktywacyjnyDataOnDemand.modifyListAktywacyjny(ListAktywacyjny obj) {
        return false;
    }
    
    public void ListAktywacyjnyDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = ListAktywacyjny.findListAktywacyjnyEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'ListAktywacyjny' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<ListAktywacyjny>();
        for (int i = 0; i < 10; i++) {
            ListAktywacyjny obj = getNewTransientListAktywacyjny(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
