// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package pl.wroc.pwr.wiz.io.psi.model;

import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;
import pl.wroc.pwr.wiz.io.psi.model.Ocena;
import pl.wroc.pwr.wiz.io.psi.model.OcenaDataOnDemand;
import pl.wroc.pwr.wiz.io.psi.model.OcenaIntegrationTest;

privileged aspect OcenaIntegrationTest_Roo_IntegrationTest {
    
    declare @type: OcenaIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: OcenaIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: OcenaIntegrationTest: @Transactional;
    
    @Autowired
    OcenaDataOnDemand OcenaIntegrationTest.dod;
    
    @Test
    public void OcenaIntegrationTest.testCountOcenas() {
        Assert.assertNotNull("Data on demand for 'Ocena' failed to initialize correctly", dod.getRandomOcena());
        long count = Ocena.countOcenas();
        Assert.assertTrue("Counter for 'Ocena' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void OcenaIntegrationTest.testFindOcena() {
        Ocena obj = dod.getRandomOcena();
        Assert.assertNotNull("Data on demand for 'Ocena' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Ocena' failed to provide an identifier", id);
        obj = Ocena.findOcena(id);
        Assert.assertNotNull("Find method for 'Ocena' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Ocena' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void OcenaIntegrationTest.testFindAllOcenas() {
        Assert.assertNotNull("Data on demand for 'Ocena' failed to initialize correctly", dod.getRandomOcena());
        long count = Ocena.countOcenas();
        Assert.assertTrue("Too expensive to perform a find all test for 'Ocena', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Ocena> result = Ocena.findAllOcenas();
        Assert.assertNotNull("Find all method for 'Ocena' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Ocena' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void OcenaIntegrationTest.testFindOcenaEntries() {
        Assert.assertNotNull("Data on demand for 'Ocena' failed to initialize correctly", dod.getRandomOcena());
        long count = Ocena.countOcenas();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Ocena> result = Ocena.findOcenaEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Ocena' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Ocena' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void OcenaIntegrationTest.testFlush() {
        Ocena obj = dod.getRandomOcena();
        Assert.assertNotNull("Data on demand for 'Ocena' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Ocena' failed to provide an identifier", id);
        obj = Ocena.findOcena(id);
        Assert.assertNotNull("Find method for 'Ocena' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyOcena(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Ocena' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void OcenaIntegrationTest.testMergeUpdate() {
        Ocena obj = dod.getRandomOcena();
        Assert.assertNotNull("Data on demand for 'Ocena' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Ocena' failed to provide an identifier", id);
        obj = Ocena.findOcena(id);
        boolean modified =  dod.modifyOcena(obj);
        Integer currentVersion = obj.getVersion();
        Ocena merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Ocena' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void OcenaIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Ocena' failed to initialize correctly", dod.getRandomOcena());
        Ocena obj = dod.getNewTransientOcena(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Ocena' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Ocena' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Ocena' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void OcenaIntegrationTest.testRemove() {
        Ocena obj = dod.getRandomOcena();
        Assert.assertNotNull("Data on demand for 'Ocena' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Ocena' failed to provide an identifier", id);
        obj = Ocena.findOcena(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Ocena' with identifier '" + id + "'", Ocena.findOcena(id));
    }
    
}
