// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package pl.wroc.pwr.wiz.io.psi.model;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;
import pl.wroc.pwr.wiz.io.psi.model.Parametr;
import pl.wroc.pwr.wiz.io.psi.model.ParametrDataOnDemand;

privileged aspect ParametrDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ParametrDataOnDemand: @Component;
    
    private Random ParametrDataOnDemand.rnd = new SecureRandom();
    
    private List<Parametr> ParametrDataOnDemand.data;
    
    public Parametr ParametrDataOnDemand.getNewTransientParametr(int index) {
        Parametr obj = new Parametr();
        setJednostka(obj, index);
        setNazwa(obj, index);
        setObligatoryjny(obj, index);
        setTyp(obj, index);
        return obj;
    }
    
    public void ParametrDataOnDemand.setJednostka(Parametr obj, int index) {
        String jednostka = "jednostka_" + index;
        obj.setJednostka(jednostka);
    }
    
    public void ParametrDataOnDemand.setNazwa(Parametr obj, int index) {
        String nazwa = "nazwa_" + index;
        obj.setNazwa(nazwa);
    }
    
    public void ParametrDataOnDemand.setObligatoryjny(Parametr obj, int index) {
        Boolean obligatoryjny = Boolean.TRUE;
        obj.setObligatoryjny(obligatoryjny);
    }
    
    public void ParametrDataOnDemand.setTyp(Parametr obj, int index) {
        Parametr typ = obj;
        obj.setTyp(typ);
    }
    
    public Parametr ParametrDataOnDemand.getSpecificParametr(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Parametr obj = data.get(index);
        Long id = obj.getId();
        return Parametr.findParametr(id);
    }
    
    public Parametr ParametrDataOnDemand.getRandomParametr() {
        init();
        Parametr obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Parametr.findParametr(id);
    }
    
    public boolean ParametrDataOnDemand.modifyParametr(Parametr obj) {
        return false;
    }
    
    public void ParametrDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Parametr.findParametrEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Parametr' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Parametr>();
        for (int i = 0; i < 10; i++) {
            Parametr obj = getNewTransientParametr(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
