// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package pl.wroc.pwr.wiz.io.psi.model;

import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;
import pl.wroc.pwr.wiz.io.psi.model.Powiadomienie;
import pl.wroc.pwr.wiz.io.psi.model.PowiadomienieDataOnDemand;
import pl.wroc.pwr.wiz.io.psi.model.PowiadomienieIntegrationTest;

privileged aspect PowiadomienieIntegrationTest_Roo_IntegrationTest {
    
    declare @type: PowiadomienieIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: PowiadomienieIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: PowiadomienieIntegrationTest: @Transactional;
    
    @Autowired
    PowiadomienieDataOnDemand PowiadomienieIntegrationTest.dod;
    
    @Test
    public void PowiadomienieIntegrationTest.testCountPowiadomienies() {
        Assert.assertNotNull("Data on demand for 'Powiadomienie' failed to initialize correctly", dod.getRandomPowiadomienie());
        long count = Powiadomienie.countPowiadomienies();
        Assert.assertTrue("Counter for 'Powiadomienie' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void PowiadomienieIntegrationTest.testFindPowiadomienie() {
        Powiadomienie obj = dod.getRandomPowiadomienie();
        Assert.assertNotNull("Data on demand for 'Powiadomienie' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Powiadomienie' failed to provide an identifier", id);
        obj = Powiadomienie.findPowiadomienie(id);
        Assert.assertNotNull("Find method for 'Powiadomienie' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Powiadomienie' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void PowiadomienieIntegrationTest.testFindAllPowiadomienies() {
        Assert.assertNotNull("Data on demand for 'Powiadomienie' failed to initialize correctly", dod.getRandomPowiadomienie());
        long count = Powiadomienie.countPowiadomienies();
        Assert.assertTrue("Too expensive to perform a find all test for 'Powiadomienie', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Powiadomienie> result = Powiadomienie.findAllPowiadomienies();
        Assert.assertNotNull("Find all method for 'Powiadomienie' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Powiadomienie' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void PowiadomienieIntegrationTest.testFindPowiadomienieEntries() {
        Assert.assertNotNull("Data on demand for 'Powiadomienie' failed to initialize correctly", dod.getRandomPowiadomienie());
        long count = Powiadomienie.countPowiadomienies();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Powiadomienie> result = Powiadomienie.findPowiadomienieEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Powiadomienie' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Powiadomienie' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void PowiadomienieIntegrationTest.testFlush() {
        Powiadomienie obj = dod.getRandomPowiadomienie();
        Assert.assertNotNull("Data on demand for 'Powiadomienie' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Powiadomienie' failed to provide an identifier", id);
        obj = Powiadomienie.findPowiadomienie(id);
        Assert.assertNotNull("Find method for 'Powiadomienie' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyPowiadomienie(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Powiadomienie' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PowiadomienieIntegrationTest.testMergeUpdate() {
        Powiadomienie obj = dod.getRandomPowiadomienie();
        Assert.assertNotNull("Data on demand for 'Powiadomienie' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Powiadomienie' failed to provide an identifier", id);
        obj = Powiadomienie.findPowiadomienie(id);
        boolean modified =  dod.modifyPowiadomienie(obj);
        Integer currentVersion = obj.getVersion();
        Powiadomienie merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Powiadomienie' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PowiadomienieIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Powiadomienie' failed to initialize correctly", dod.getRandomPowiadomienie());
        Powiadomienie obj = dod.getNewTransientPowiadomienie(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Powiadomienie' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Powiadomienie' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Powiadomienie' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void PowiadomienieIntegrationTest.testRemove() {
        Powiadomienie obj = dod.getRandomPowiadomienie();
        Assert.assertNotNull("Data on demand for 'Powiadomienie' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Powiadomienie' failed to provide an identifier", id);
        obj = Powiadomienie.findPowiadomienie(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Powiadomienie' with identifier '" + id + "'", Powiadomienie.findPowiadomienie(id));
    }
    
}
