// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package pl.wroc.pwr.wiz.io.psi.model;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import pl.wroc.pwr.wiz.io.psi.model.KategoriaPowoduDataOnDemand;
import pl.wroc.pwr.wiz.io.psi.model.PowodZgloszenia;
import pl.wroc.pwr.wiz.io.psi.model.PowodZgloszeniaDataOnDemand;

privileged aspect PowodZgloszeniaDataOnDemand_Roo_DataOnDemand {
    
    declare @type: PowodZgloszeniaDataOnDemand: @Component;
    
    private Random PowodZgloszeniaDataOnDemand.rnd = new SecureRandom();
    
    private List<PowodZgloszenia> PowodZgloszeniaDataOnDemand.data;
    
    @Autowired
    KategoriaPowoduDataOnDemand PowodZgloszeniaDataOnDemand.kategoriaPowoduDataOnDemand;
    
    public PowodZgloszenia PowodZgloszeniaDataOnDemand.getNewTransientPowodZgloszenia(int index) {
        PowodZgloszenia obj = new PowodZgloszenia();
        setTresc(obj, index);
        return obj;
    }
    
    public void PowodZgloszeniaDataOnDemand.setTresc(PowodZgloszenia obj, int index) {
        String tresc = "tresc_" + index;
        obj.setTresc(tresc);
    }
    
    public PowodZgloszenia PowodZgloszeniaDataOnDemand.getSpecificPowodZgloszenia(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        PowodZgloszenia obj = data.get(index);
        Long id = obj.getId();
        return PowodZgloszenia.findPowodZgloszenia(id);
    }
    
    public PowodZgloszenia PowodZgloszeniaDataOnDemand.getRandomPowodZgloszenia() {
        init();
        PowodZgloszenia obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return PowodZgloszenia.findPowodZgloszenia(id);
    }
    
    public boolean PowodZgloszeniaDataOnDemand.modifyPowodZgloszenia(PowodZgloszenia obj) {
        return false;
    }
    
    public void PowodZgloszeniaDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = PowodZgloszenia.findPowodZgloszeniaEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'PowodZgloszenia' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<PowodZgloszenia>();
        for (int i = 0; i < 10; i++) {
            PowodZgloszenia obj = getNewTransientPowodZgloszenia(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
