// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package pl.wroc.pwr.wiz.io.psi.model;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;
import pl.wroc.pwr.wiz.io.psi.model.PowodOceny;
import pl.wroc.pwr.wiz.io.psi.model.PowodOcenyDataOnDemand;

privileged aspect PowodOcenyDataOnDemand_Roo_DataOnDemand {
    
    declare @type: PowodOcenyDataOnDemand: @Component;
    
    private Random PowodOcenyDataOnDemand.rnd = new SecureRandom();
    
    private List<PowodOceny> PowodOcenyDataOnDemand.data;
    
    public PowodOceny PowodOcenyDataOnDemand.getNewTransientPowodOceny(int index) {
        PowodOceny obj = new PowodOceny();
        setPowod(obj, index);
        return obj;
    }
    
    public void PowodOcenyDataOnDemand.setPowod(PowodOceny obj, int index) {
        String powod = "powod_" + index;
        obj.setPowod(powod);
    }
    
    public PowodOceny PowodOcenyDataOnDemand.getSpecificPowodOceny(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        PowodOceny obj = data.get(index);
        Long id = obj.getId();
        return PowodOceny.findPowodOceny(id);
    }
    
    public PowodOceny PowodOcenyDataOnDemand.getRandomPowodOceny() {
        init();
        PowodOceny obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return PowodOceny.findPowodOceny(id);
    }
    
    public boolean PowodOcenyDataOnDemand.modifyPowodOceny(PowodOceny obj) {
        return false;
    }
    
    public void PowodOcenyDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = PowodOceny.findPowodOcenyEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'PowodOceny' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<PowodOceny>();
        for (int i = 0; i < 10; i++) {
            PowodOceny obj = getNewTransientPowodOceny(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
