// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package pl.wroc.pwr.wiz.io.psi.model;

import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;
import pl.wroc.pwr.wiz.io.psi.model.PowodOceny;
import pl.wroc.pwr.wiz.io.psi.model.PowodOcenyDataOnDemand;
import pl.wroc.pwr.wiz.io.psi.model.PowodOcenyIntegrationTest;

privileged aspect PowodOcenyIntegrationTest_Roo_IntegrationTest {
    
    declare @type: PowodOcenyIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: PowodOcenyIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: PowodOcenyIntegrationTest: @Transactional;
    
    @Autowired
    PowodOcenyDataOnDemand PowodOcenyIntegrationTest.dod;
    
    @Test
    public void PowodOcenyIntegrationTest.testCountPowodOcenys() {
        Assert.assertNotNull("Data on demand for 'PowodOceny' failed to initialize correctly", dod.getRandomPowodOceny());
        long count = PowodOceny.countPowodOcenys();
        Assert.assertTrue("Counter for 'PowodOceny' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void PowodOcenyIntegrationTest.testFindPowodOceny() {
        PowodOceny obj = dod.getRandomPowodOceny();
        Assert.assertNotNull("Data on demand for 'PowodOceny' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'PowodOceny' failed to provide an identifier", id);
        obj = PowodOceny.findPowodOceny(id);
        Assert.assertNotNull("Find method for 'PowodOceny' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'PowodOceny' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void PowodOcenyIntegrationTest.testFindAllPowodOcenys() {
        Assert.assertNotNull("Data on demand for 'PowodOceny' failed to initialize correctly", dod.getRandomPowodOceny());
        long count = PowodOceny.countPowodOcenys();
        Assert.assertTrue("Too expensive to perform a find all test for 'PowodOceny', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<PowodOceny> result = PowodOceny.findAllPowodOcenys();
        Assert.assertNotNull("Find all method for 'PowodOceny' illegally returned null", result);
        Assert.assertTrue("Find all method for 'PowodOceny' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void PowodOcenyIntegrationTest.testFindPowodOcenyEntries() {
        Assert.assertNotNull("Data on demand for 'PowodOceny' failed to initialize correctly", dod.getRandomPowodOceny());
        long count = PowodOceny.countPowodOcenys();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<PowodOceny> result = PowodOceny.findPowodOcenyEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'PowodOceny' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'PowodOceny' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void PowodOcenyIntegrationTest.testFlush() {
        PowodOceny obj = dod.getRandomPowodOceny();
        Assert.assertNotNull("Data on demand for 'PowodOceny' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'PowodOceny' failed to provide an identifier", id);
        obj = PowodOceny.findPowodOceny(id);
        Assert.assertNotNull("Find method for 'PowodOceny' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyPowodOceny(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'PowodOceny' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PowodOcenyIntegrationTest.testMergeUpdate() {
        PowodOceny obj = dod.getRandomPowodOceny();
        Assert.assertNotNull("Data on demand for 'PowodOceny' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'PowodOceny' failed to provide an identifier", id);
        obj = PowodOceny.findPowodOceny(id);
        boolean modified =  dod.modifyPowodOceny(obj);
        Integer currentVersion = obj.getVersion();
        PowodOceny merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'PowodOceny' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PowodOcenyIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'PowodOceny' failed to initialize correctly", dod.getRandomPowodOceny());
        PowodOceny obj = dod.getNewTransientPowodOceny(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'PowodOceny' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'PowodOceny' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'PowodOceny' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void PowodOcenyIntegrationTest.testRemove() {
        PowodOceny obj = dod.getRandomPowodOceny();
        Assert.assertNotNull("Data on demand for 'PowodOceny' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'PowodOceny' failed to provide an identifier", id);
        obj = PowodOceny.findPowodOceny(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'PowodOceny' with identifier '" + id + "'", PowodOceny.findPowodOceny(id));
    }
    
}
