// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package pl.wroc.pwr.wiz.io.psi.model;

import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;
import pl.wroc.pwr.wiz.io.psi.model.RegulaminDataOnDemand;
import pl.wroc.pwr.wiz.io.psi.model.RegulaminIntegrationTest;
import pl.wroc.pwr.wiz.io.psi.service.dao.RegulaminService;

privileged aspect RegulaminIntegrationTest_Roo_IntegrationTest {
    
    declare @type: RegulaminIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: RegulaminIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: RegulaminIntegrationTest: @Transactional;
    
    @Autowired
    RegulaminDataOnDemand RegulaminIntegrationTest.dod;
    
    @Autowired
    RegulaminService RegulaminIntegrationTest.regulaminService;
    
    @Test
    public void RegulaminIntegrationTest.testCountAllRegulamins() {
        Assert.assertNotNull("Data on demand for 'Regulamin' failed to initialize correctly", dod.getRandomRegulamin());
        long count = regulaminService.countAllRegulamins();
        Assert.assertTrue("Counter for 'Regulamin' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void RegulaminIntegrationTest.testFindRegulamin() {
        Regulamin obj = dod.getRandomRegulamin();
        Assert.assertNotNull("Data on demand for 'Regulamin' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Regulamin' failed to provide an identifier", id);
        obj = regulaminService.findRegulamin(id);
        Assert.assertNotNull("Find method for 'Regulamin' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Regulamin' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void RegulaminIntegrationTest.testFindAllRegulamins() {
        Assert.assertNotNull("Data on demand for 'Regulamin' failed to initialize correctly", dod.getRandomRegulamin());
        long count = regulaminService.countAllRegulamins();
        Assert.assertTrue("Too expensive to perform a find all test for 'Regulamin', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Regulamin> result = regulaminService.findAllRegulamins();
        Assert.assertNotNull("Find all method for 'Regulamin' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Regulamin' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void RegulaminIntegrationTest.testFindRegulaminEntries() {
        Assert.assertNotNull("Data on demand for 'Regulamin' failed to initialize correctly", dod.getRandomRegulamin());
        long count = regulaminService.countAllRegulamins();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Regulamin> result = regulaminService.findRegulaminEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Regulamin' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Regulamin' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void RegulaminIntegrationTest.testFlush() {
        Regulamin obj = dod.getRandomRegulamin();
        Assert.assertNotNull("Data on demand for 'Regulamin' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Regulamin' failed to provide an identifier", id);
        obj = regulaminService.findRegulamin(id);
        Assert.assertNotNull("Find method for 'Regulamin' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyRegulamin(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Regulamin' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void RegulaminIntegrationTest.testUpdateRegulaminUpdate() {
        Regulamin obj = dod.getRandomRegulamin();
        Assert.assertNotNull("Data on demand for 'Regulamin' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Regulamin' failed to provide an identifier", id);
        obj = regulaminService.findRegulamin(id);
        boolean modified =  dod.modifyRegulamin(obj);
        Integer currentVersion = obj.getVersion();
        Regulamin merged = regulaminService.updateRegulamin(obj);
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Regulamin' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void RegulaminIntegrationTest.testSaveRegulamin() {
        Assert.assertNotNull("Data on demand for 'Regulamin' failed to initialize correctly", dod.getRandomRegulamin());
        Regulamin obj = dod.getNewTransientRegulamin(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Regulamin' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Regulamin' identifier to be null", obj.getId());
        try {
            regulaminService.saveRegulamin(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Regulamin' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void RegulaminIntegrationTest.testDeleteRegulamin() {
        Regulamin obj = dod.getRandomRegulamin();
        Assert.assertNotNull("Data on demand for 'Regulamin' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Regulamin' failed to provide an identifier", id);
        obj = regulaminService.findRegulamin(id);
        regulaminService.deleteRegulamin(obj);
        obj.flush();
        Assert.assertNull("Failed to remove 'Regulamin' with identifier '" + id + "'", regulaminService.findRegulamin(id));
    }
    
}
