// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package pl.wroc.pwr.wiz.io.psi.model;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;
import pl.wroc.pwr.wiz.io.psi.model.RodzajPlatnosci;
import pl.wroc.pwr.wiz.io.psi.model.SposobDostawy;
import pl.wroc.pwr.wiz.io.psi.model.SposobDostawyDataOnDemand;

privileged aspect SposobDostawyDataOnDemand_Roo_DataOnDemand {
    
    declare @type: SposobDostawyDataOnDemand: @Component;
    
    private Random SposobDostawyDataOnDemand.rnd = new SecureRandom();
    
    private List<SposobDostawy> SposobDostawyDataOnDemand.data;
    
    public SposobDostawy SposobDostawyDataOnDemand.getNewTransientSposobDostawy(int index) {
        SposobDostawy obj = new SposobDostawy();
        setCzasDostawy(obj, index);
        setEdytowalny(obj, index);
        setNazwa(obj, index);
        setRodzajPlatnosci(obj, index);
        return obj;
    }
    
    public void SposobDostawyDataOnDemand.setCzasDostawy(SposobDostawy obj, int index) {
        int czasDostawy = index;
        obj.setCzasDostawy(czasDostawy);
    }
    
    public void SposobDostawyDataOnDemand.setEdytowalny(SposobDostawy obj, int index) {
        Boolean edytowalny = Boolean.TRUE;
        obj.setEdytowalny(edytowalny);
    }
    
    public void SposobDostawyDataOnDemand.setNazwa(SposobDostawy obj, int index) {
        String nazwa = "nazwa_" + index;
        obj.setNazwa(nazwa);
    }
    
    public void SposobDostawyDataOnDemand.setRodzajPlatnosci(SposobDostawy obj, int index) {
        RodzajPlatnosci rodzajPlatnosci = RodzajPlatnosci.class.getEnumConstants()[0];
        obj.setRodzajPlatnosci(rodzajPlatnosci);
    }
    
    public SposobDostawy SposobDostawyDataOnDemand.getSpecificSposobDostawy(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        SposobDostawy obj = data.get(index);
        Long id = obj.getId();
        return SposobDostawy.findSposobDostawy(id);
    }
    
    public SposobDostawy SposobDostawyDataOnDemand.getRandomSposobDostawy() {
        init();
        SposobDostawy obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return SposobDostawy.findSposobDostawy(id);
    }
    
    public boolean SposobDostawyDataOnDemand.modifySposobDostawy(SposobDostawy obj) {
        return false;
    }
    
    public void SposobDostawyDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = SposobDostawy.findSposobDostawyEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'SposobDostawy' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<SposobDostawy>();
        for (int i = 0; i < 10; i++) {
            SposobDostawy obj = getNewTransientSposobDostawy(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
