// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package pl.wroc.pwr.wiz.io.psi.model;

import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;
import pl.wroc.pwr.wiz.io.psi.model.SposobDostawy;
import pl.wroc.pwr.wiz.io.psi.model.SposobDostawyDataOnDemand;
import pl.wroc.pwr.wiz.io.psi.model.SposobDostawyIntegrationTest;

privileged aspect SposobDostawyIntegrationTest_Roo_IntegrationTest {
    
    declare @type: SposobDostawyIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: SposobDostawyIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: SposobDostawyIntegrationTest: @Transactional;
    
    @Autowired
    SposobDostawyDataOnDemand SposobDostawyIntegrationTest.dod;
    
    @Test
    public void SposobDostawyIntegrationTest.testCountSposobDostawys() {
        Assert.assertNotNull("Data on demand for 'SposobDostawy' failed to initialize correctly", dod.getRandomSposobDostawy());
        long count = SposobDostawy.countSposobDostawys();
        Assert.assertTrue("Counter for 'SposobDostawy' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void SposobDostawyIntegrationTest.testFindSposobDostawy() {
        SposobDostawy obj = dod.getRandomSposobDostawy();
        Assert.assertNotNull("Data on demand for 'SposobDostawy' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'SposobDostawy' failed to provide an identifier", id);
        obj = SposobDostawy.findSposobDostawy(id);
        Assert.assertNotNull("Find method for 'SposobDostawy' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'SposobDostawy' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void SposobDostawyIntegrationTest.testFindAllSposobDostawys() {
        Assert.assertNotNull("Data on demand for 'SposobDostawy' failed to initialize correctly", dod.getRandomSposobDostawy());
        long count = SposobDostawy.countSposobDostawys();
        Assert.assertTrue("Too expensive to perform a find all test for 'SposobDostawy', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<SposobDostawy> result = SposobDostawy.findAllSposobDostawys();
        Assert.assertNotNull("Find all method for 'SposobDostawy' illegally returned null", result);
        Assert.assertTrue("Find all method for 'SposobDostawy' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void SposobDostawyIntegrationTest.testFindSposobDostawyEntries() {
        Assert.assertNotNull("Data on demand for 'SposobDostawy' failed to initialize correctly", dod.getRandomSposobDostawy());
        long count = SposobDostawy.countSposobDostawys();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<SposobDostawy> result = SposobDostawy.findSposobDostawyEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'SposobDostawy' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'SposobDostawy' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void SposobDostawyIntegrationTest.testFlush() {
        SposobDostawy obj = dod.getRandomSposobDostawy();
        Assert.assertNotNull("Data on demand for 'SposobDostawy' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'SposobDostawy' failed to provide an identifier", id);
        obj = SposobDostawy.findSposobDostawy(id);
        Assert.assertNotNull("Find method for 'SposobDostawy' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifySposobDostawy(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'SposobDostawy' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void SposobDostawyIntegrationTest.testMergeUpdate() {
        SposobDostawy obj = dod.getRandomSposobDostawy();
        Assert.assertNotNull("Data on demand for 'SposobDostawy' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'SposobDostawy' failed to provide an identifier", id);
        obj = SposobDostawy.findSposobDostawy(id);
        boolean modified =  dod.modifySposobDostawy(obj);
        Integer currentVersion = obj.getVersion();
        SposobDostawy merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'SposobDostawy' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void SposobDostawyIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'SposobDostawy' failed to initialize correctly", dod.getRandomSposobDostawy());
        SposobDostawy obj = dod.getNewTransientSposobDostawy(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'SposobDostawy' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'SposobDostawy' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'SposobDostawy' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void SposobDostawyIntegrationTest.testRemove() {
        SposobDostawy obj = dod.getRandomSposobDostawy();
        Assert.assertNotNull("Data on demand for 'SposobDostawy' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'SposobDostawy' failed to provide an identifier", id);
        obj = SposobDostawy.findSposobDostawy(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'SposobDostawy' with identifier '" + id + "'", SposobDostawy.findSposobDostawy(id));
    }
    
}
