// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package pl.wroc.pwr.wiz.io.psi.model;

import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;
import pl.wroc.pwr.wiz.io.psi.model.SzczegolyDostawy;
import pl.wroc.pwr.wiz.io.psi.model.SzczegolyDostawyDataOnDemand;
import pl.wroc.pwr.wiz.io.psi.model.SzczegolyDostawyIntegrationTest;

privileged aspect SzczegolyDostawyIntegrationTest_Roo_IntegrationTest {
    
    declare @type: SzczegolyDostawyIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: SzczegolyDostawyIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: SzczegolyDostawyIntegrationTest: @Transactional;
    
    @Autowired
    SzczegolyDostawyDataOnDemand SzczegolyDostawyIntegrationTest.dod;
    
    @Test
    public void SzczegolyDostawyIntegrationTest.testCountSzczegolyDostawys() {
        Assert.assertNotNull("Data on demand for 'SzczegolyDostawy' failed to initialize correctly", dod.getRandomSzczegolyDostawy());
        long count = SzczegolyDostawy.countSzczegolyDostawys();
        Assert.assertTrue("Counter for 'SzczegolyDostawy' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void SzczegolyDostawyIntegrationTest.testFindSzczegolyDostawy() {
        SzczegolyDostawy obj = dod.getRandomSzczegolyDostawy();
        Assert.assertNotNull("Data on demand for 'SzczegolyDostawy' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'SzczegolyDostawy' failed to provide an identifier", id);
        obj = SzczegolyDostawy.findSzczegolyDostawy(id);
        Assert.assertNotNull("Find method for 'SzczegolyDostawy' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'SzczegolyDostawy' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void SzczegolyDostawyIntegrationTest.testFindAllSzczegolyDostawys() {
        Assert.assertNotNull("Data on demand for 'SzczegolyDostawy' failed to initialize correctly", dod.getRandomSzczegolyDostawy());
        long count = SzczegolyDostawy.countSzczegolyDostawys();
        Assert.assertTrue("Too expensive to perform a find all test for 'SzczegolyDostawy', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<SzczegolyDostawy> result = SzczegolyDostawy.findAllSzczegolyDostawys();
        Assert.assertNotNull("Find all method for 'SzczegolyDostawy' illegally returned null", result);
        Assert.assertTrue("Find all method for 'SzczegolyDostawy' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void SzczegolyDostawyIntegrationTest.testFindSzczegolyDostawyEntries() {
        Assert.assertNotNull("Data on demand for 'SzczegolyDostawy' failed to initialize correctly", dod.getRandomSzczegolyDostawy());
        long count = SzczegolyDostawy.countSzczegolyDostawys();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<SzczegolyDostawy> result = SzczegolyDostawy.findSzczegolyDostawyEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'SzczegolyDostawy' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'SzczegolyDostawy' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void SzczegolyDostawyIntegrationTest.testFlush() {
        SzczegolyDostawy obj = dod.getRandomSzczegolyDostawy();
        Assert.assertNotNull("Data on demand for 'SzczegolyDostawy' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'SzczegolyDostawy' failed to provide an identifier", id);
        obj = SzczegolyDostawy.findSzczegolyDostawy(id);
        Assert.assertNotNull("Find method for 'SzczegolyDostawy' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifySzczegolyDostawy(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'SzczegolyDostawy' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void SzczegolyDostawyIntegrationTest.testMergeUpdate() {
        SzczegolyDostawy obj = dod.getRandomSzczegolyDostawy();
        Assert.assertNotNull("Data on demand for 'SzczegolyDostawy' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'SzczegolyDostawy' failed to provide an identifier", id);
        obj = SzczegolyDostawy.findSzczegolyDostawy(id);
        boolean modified =  dod.modifySzczegolyDostawy(obj);
        Integer currentVersion = obj.getVersion();
        SzczegolyDostawy merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'SzczegolyDostawy' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void SzczegolyDostawyIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'SzczegolyDostawy' failed to initialize correctly", dod.getRandomSzczegolyDostawy());
        SzczegolyDostawy obj = dod.getNewTransientSzczegolyDostawy(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'SzczegolyDostawy' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'SzczegolyDostawy' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'SzczegolyDostawy' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void SzczegolyDostawyIntegrationTest.testRemove() {
        SzczegolyDostawy obj = dod.getRandomSzczegolyDostawy();
        Assert.assertNotNull("Data on demand for 'SzczegolyDostawy' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'SzczegolyDostawy' failed to provide an identifier", id);
        obj = SzczegolyDostawy.findSzczegolyDostawy(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'SzczegolyDostawy' with identifier '" + id + "'", SzczegolyDostawy.findSzczegolyDostawy(id));
    }
    
}
