// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package pl.wroc.pwr.wiz.io.psi.model;

import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;
import pl.wroc.pwr.wiz.io.psi.model.SzczegolyWykluczenia;
import pl.wroc.pwr.wiz.io.psi.model.SzczegolyWykluczeniaDataOnDemand;
import pl.wroc.pwr.wiz.io.psi.model.SzczegolyWykluczeniaIntegrationTest;

privileged aspect SzczegolyWykluczeniaIntegrationTest_Roo_IntegrationTest {
    
    declare @type: SzczegolyWykluczeniaIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: SzczegolyWykluczeniaIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: SzczegolyWykluczeniaIntegrationTest: @Transactional;
    
    @Autowired
    SzczegolyWykluczeniaDataOnDemand SzczegolyWykluczeniaIntegrationTest.dod;
    
    @Test
    public void SzczegolyWykluczeniaIntegrationTest.testCountSzczegolyWykluczenias() {
        Assert.assertNotNull("Data on demand for 'SzczegolyWykluczenia' failed to initialize correctly", dod.getRandomSzczegolyWykluczenia());
        long count = SzczegolyWykluczenia.countSzczegolyWykluczenias();
        Assert.assertTrue("Counter for 'SzczegolyWykluczenia' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void SzczegolyWykluczeniaIntegrationTest.testFindSzczegolyWykluczenia() {
        SzczegolyWykluczenia obj = dod.getRandomSzczegolyWykluczenia();
        Assert.assertNotNull("Data on demand for 'SzczegolyWykluczenia' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'SzczegolyWykluczenia' failed to provide an identifier", id);
        obj = SzczegolyWykluczenia.findSzczegolyWykluczenia(id);
        Assert.assertNotNull("Find method for 'SzczegolyWykluczenia' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'SzczegolyWykluczenia' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void SzczegolyWykluczeniaIntegrationTest.testFindAllSzczegolyWykluczenias() {
        Assert.assertNotNull("Data on demand for 'SzczegolyWykluczenia' failed to initialize correctly", dod.getRandomSzczegolyWykluczenia());
        long count = SzczegolyWykluczenia.countSzczegolyWykluczenias();
        Assert.assertTrue("Too expensive to perform a find all test for 'SzczegolyWykluczenia', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<SzczegolyWykluczenia> result = SzczegolyWykluczenia.findAllSzczegolyWykluczenias();
        Assert.assertNotNull("Find all method for 'SzczegolyWykluczenia' illegally returned null", result);
        Assert.assertTrue("Find all method for 'SzczegolyWykluczenia' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void SzczegolyWykluczeniaIntegrationTest.testFindSzczegolyWykluczeniaEntries() {
        Assert.assertNotNull("Data on demand for 'SzczegolyWykluczenia' failed to initialize correctly", dod.getRandomSzczegolyWykluczenia());
        long count = SzczegolyWykluczenia.countSzczegolyWykluczenias();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<SzczegolyWykluczenia> result = SzczegolyWykluczenia.findSzczegolyWykluczeniaEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'SzczegolyWykluczenia' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'SzczegolyWykluczenia' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void SzczegolyWykluczeniaIntegrationTest.testFlush() {
        SzczegolyWykluczenia obj = dod.getRandomSzczegolyWykluczenia();
        Assert.assertNotNull("Data on demand for 'SzczegolyWykluczenia' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'SzczegolyWykluczenia' failed to provide an identifier", id);
        obj = SzczegolyWykluczenia.findSzczegolyWykluczenia(id);
        Assert.assertNotNull("Find method for 'SzczegolyWykluczenia' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifySzczegolyWykluczenia(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'SzczegolyWykluczenia' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void SzczegolyWykluczeniaIntegrationTest.testMergeUpdate() {
        SzczegolyWykluczenia obj = dod.getRandomSzczegolyWykluczenia();
        Assert.assertNotNull("Data on demand for 'SzczegolyWykluczenia' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'SzczegolyWykluczenia' failed to provide an identifier", id);
        obj = SzczegolyWykluczenia.findSzczegolyWykluczenia(id);
        boolean modified =  dod.modifySzczegolyWykluczenia(obj);
        Integer currentVersion = obj.getVersion();
        SzczegolyWykluczenia merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'SzczegolyWykluczenia' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void SzczegolyWykluczeniaIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'SzczegolyWykluczenia' failed to initialize correctly", dod.getRandomSzczegolyWykluczenia());
        SzczegolyWykluczenia obj = dod.getNewTransientSzczegolyWykluczenia(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'SzczegolyWykluczenia' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'SzczegolyWykluczenia' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'SzczegolyWykluczenia' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void SzczegolyWykluczeniaIntegrationTest.testRemove() {
        SzczegolyWykluczenia obj = dod.getRandomSzczegolyWykluczenia();
        Assert.assertNotNull("Data on demand for 'SzczegolyWykluczenia' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'SzczegolyWykluczenia' failed to provide an identifier", id);
        obj = SzczegolyWykluczenia.findSzczegolyWykluczenia(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'SzczegolyWykluczenia' with identifier '" + id + "'", SzczegolyWykluczenia.findSzczegolyWykluczenia(id));
    }
    
}
