// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package pl.wroc.pwr.wiz.io.psi.model;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;
import pl.wroc.pwr.wiz.io.psi.model.SzczegolyDostawy;
import pl.wroc.pwr.wiz.io.psi.model.SzczegolyDostawyDataOnDemand;

privileged aspect SzczegolyDostawyDataOnDemand_Roo_DataOnDemand {
    
    declare @type: SzczegolyDostawyDataOnDemand: @Component;
    
    private Random SzczegolyDostawyDataOnDemand.rnd = new SecureRandom();
    
    private List<SzczegolyDostawy> SzczegolyDostawyDataOnDemand.data;
    
    public SzczegolyDostawy SzczegolyDostawyDataOnDemand.getNewTransientSzczegolyDostawy(int index) {
        SzczegolyDostawy obj = new SzczegolyDostawy();
        setKosztKolejnejSztuki(obj, index);
        setKosztPierwszejSztuki(obj, index);
        setLiczbaWPaczce(obj, index);
        return obj;
    }
    
    public void SzczegolyDostawyDataOnDemand.setKosztKolejnejSztuki(SzczegolyDostawy obj, int index) {
        double kosztKolejnejSztuki = new Integer(index).doubleValue();
        obj.setKosztKolejnejSztuki(kosztKolejnejSztuki);
    }
    
    public void SzczegolyDostawyDataOnDemand.setKosztPierwszejSztuki(SzczegolyDostawy obj, int index) {
        double kosztPierwszejSztuki = new Integer(index).doubleValue();
        obj.setKosztPierwszejSztuki(kosztPierwszejSztuki);
    }
    
    public void SzczegolyDostawyDataOnDemand.setLiczbaWPaczce(SzczegolyDostawy obj, int index) {
        int liczbaWPaczce = index;
        obj.setLiczbaWPaczce(liczbaWPaczce);
    }
    
    public SzczegolyDostawy SzczegolyDostawyDataOnDemand.getSpecificSzczegolyDostawy(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        SzczegolyDostawy obj = data.get(index);
        Long id = obj.getId();
        return SzczegolyDostawy.findSzczegolyDostawy(id);
    }
    
    public SzczegolyDostawy SzczegolyDostawyDataOnDemand.getRandomSzczegolyDostawy() {
        init();
        SzczegolyDostawy obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return SzczegolyDostawy.findSzczegolyDostawy(id);
    }
    
    public boolean SzczegolyDostawyDataOnDemand.modifySzczegolyDostawy(SzczegolyDostawy obj) {
        return false;
    }
    
    public void SzczegolyDostawyDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = SzczegolyDostawy.findSzczegolyDostawyEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'SzczegolyDostawy' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<SzczegolyDostawy>();
        for (int i = 0; i < 10; i++) {
            SzczegolyDostawy obj = getNewTransientSzczegolyDostawy(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
