// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package pl.wroc.pwr.wiz.io.psi.model;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;
import pl.wroc.pwr.wiz.io.psi.model.SzczegolyObserwacji;
import pl.wroc.pwr.wiz.io.psi.model.SzczegolyObserwacjiDataOnDemand;
import pl.wroc.pwr.wiz.io.psi.model.TerminPrzypomnienia;

privileged aspect SzczegolyObserwacjiDataOnDemand_Roo_DataOnDemand {
    
    declare @type: SzczegolyObserwacjiDataOnDemand: @Component;
    
    private Random SzczegolyObserwacjiDataOnDemand.rnd = new SecureRandom();
    
    private List<SzczegolyObserwacji> SzczegolyObserwacjiDataOnDemand.data;
    
    public SzczegolyObserwacji SzczegolyObserwacjiDataOnDemand.getNewTransientSzczegolyObserwacji(int index) {
        SzczegolyObserwacji obj = new SzczegolyObserwacji();
        setPrzypomnienie(obj, index);
        return obj;
    }
    
    public void SzczegolyObserwacjiDataOnDemand.setPrzypomnienie(SzczegolyObserwacji obj, int index) {
        TerminPrzypomnienia przypomnienie = TerminPrzypomnienia.class.getEnumConstants()[0];
        obj.setPrzypomnienie(przypomnienie);
    }
    
    public SzczegolyObserwacji SzczegolyObserwacjiDataOnDemand.getSpecificSzczegolyObserwacji(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        SzczegolyObserwacji obj = data.get(index);
        Long id = obj.getId();
        return SzczegolyObserwacji.findSzczegolyObserwacji(id);
    }
    
    public SzczegolyObserwacji SzczegolyObserwacjiDataOnDemand.getRandomSzczegolyObserwacji() {
        init();
        SzczegolyObserwacji obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return SzczegolyObserwacji.findSzczegolyObserwacji(id);
    }
    
    public boolean SzczegolyObserwacjiDataOnDemand.modifySzczegolyObserwacji(SzczegolyObserwacji obj) {
        return false;
    }
    
    public void SzczegolyObserwacjiDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = SzczegolyObserwacji.findSzczegolyObserwacjiEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'SzczegolyObserwacji' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<SzczegolyObserwacji>();
        for (int i = 0; i < 10; i++) {
            SzczegolyObserwacji obj = getNewTransientSzczegolyObserwacji(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
