// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package pl.wroc.pwr.wiz.io.psi.model;

import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;
import pl.wroc.pwr.wiz.io.psi.model.Szczegoly;
import pl.wroc.pwr.wiz.io.psi.model.SzczegolyDataOnDemand;
import pl.wroc.pwr.wiz.io.psi.model.SzczegolyIntegrationTest;

privileged aspect SzczegolyIntegrationTest_Roo_IntegrationTest {
    
    declare @type: SzczegolyIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: SzczegolyIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: SzczegolyIntegrationTest: @Transactional;
    
    @Autowired
    SzczegolyDataOnDemand SzczegolyIntegrationTest.dod;
    
    @Test
    public void SzczegolyIntegrationTest.testCountSzczegolys() {
        Assert.assertNotNull("Data on demand for 'Szczegoly' failed to initialize correctly", dod.getRandomSzczegoly());
        long count = Szczegoly.countSzczegolys();
        Assert.assertTrue("Counter for 'Szczegoly' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void SzczegolyIntegrationTest.testFindSzczegoly() {
        Szczegoly obj = dod.getRandomSzczegoly();
        Assert.assertNotNull("Data on demand for 'Szczegoly' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Szczegoly' failed to provide an identifier", id);
        obj = Szczegoly.findSzczegoly(id);
        Assert.assertNotNull("Find method for 'Szczegoly' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Szczegoly' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void SzczegolyIntegrationTest.testFindAllSzczegolys() {
        Assert.assertNotNull("Data on demand for 'Szczegoly' failed to initialize correctly", dod.getRandomSzczegoly());
        long count = Szczegoly.countSzczegolys();
        Assert.assertTrue("Too expensive to perform a find all test for 'Szczegoly', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Szczegoly> result = Szczegoly.findAllSzczegolys();
        Assert.assertNotNull("Find all method for 'Szczegoly' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Szczegoly' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void SzczegolyIntegrationTest.testFindSzczegolyEntries() {
        Assert.assertNotNull("Data on demand for 'Szczegoly' failed to initialize correctly", dod.getRandomSzczegoly());
        long count = Szczegoly.countSzczegolys();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Szczegoly> result = Szczegoly.findSzczegolyEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Szczegoly' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Szczegoly' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void SzczegolyIntegrationTest.testFlush() {
        Szczegoly obj = dod.getRandomSzczegoly();
        Assert.assertNotNull("Data on demand for 'Szczegoly' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Szczegoly' failed to provide an identifier", id);
        obj = Szczegoly.findSzczegoly(id);
        Assert.assertNotNull("Find method for 'Szczegoly' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifySzczegoly(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Szczegoly' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void SzczegolyIntegrationTest.testMergeUpdate() {
        Szczegoly obj = dod.getRandomSzczegoly();
        Assert.assertNotNull("Data on demand for 'Szczegoly' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Szczegoly' failed to provide an identifier", id);
        obj = Szczegoly.findSzczegoly(id);
        boolean modified =  dod.modifySzczegoly(obj);
        Integer currentVersion = obj.getVersion();
        Szczegoly merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Szczegoly' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void SzczegolyIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Szczegoly' failed to initialize correctly", dod.getRandomSzczegoly());
        Szczegoly obj = dod.getNewTransientSzczegoly(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Szczegoly' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Szczegoly' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Szczegoly' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void SzczegolyIntegrationTest.testRemove() {
        Szczegoly obj = dod.getRandomSzczegoly();
        Assert.assertNotNull("Data on demand for 'Szczegoly' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Szczegoly' failed to provide an identifier", id);
        obj = Szczegoly.findSzczegoly(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Szczegoly' with identifier '" + id + "'", Szczegoly.findSzczegoly(id));
    }
    
}
