// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package pl.wroc.pwr.wiz.io.psi.model;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;
import pl.wroc.pwr.wiz.io.psi.model.SzczegolyWykluczenia;
import pl.wroc.pwr.wiz.io.psi.model.SzczegolyWykluczeniaDataOnDemand;

privileged aspect SzczegolyWykluczeniaDataOnDemand_Roo_DataOnDemand {
    
    declare @type: SzczegolyWykluczeniaDataOnDemand: @Component;
    
    private Random SzczegolyWykluczeniaDataOnDemand.rnd = new SecureRandom();
    
    private List<SzczegolyWykluczenia> SzczegolyWykluczeniaDataOnDemand.data;
    
    public SzczegolyWykluczenia SzczegolyWykluczeniaDataOnDemand.getNewTransientSzczegolyWykluczenia(int index) {
        SzczegolyWykluczenia obj = new SzczegolyWykluczenia();
        setNotatka(obj, index);
        return obj;
    }
    
    public void SzczegolyWykluczeniaDataOnDemand.setNotatka(SzczegolyWykluczenia obj, int index) {
        String notatka = "notatka_" + index;
        obj.setNotatka(notatka);
    }
    
    public SzczegolyWykluczenia SzczegolyWykluczeniaDataOnDemand.getSpecificSzczegolyWykluczenia(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        SzczegolyWykluczenia obj = data.get(index);
        Long id = obj.getId();
        return SzczegolyWykluczenia.findSzczegolyWykluczenia(id);
    }
    
    public SzczegolyWykluczenia SzczegolyWykluczeniaDataOnDemand.getRandomSzczegolyWykluczenia() {
        init();
        SzczegolyWykluczenia obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return SzczegolyWykluczenia.findSzczegolyWykluczenia(id);
    }
    
    public boolean SzczegolyWykluczeniaDataOnDemand.modifySzczegolyWykluczenia(SzczegolyWykluczenia obj) {
        return false;
    }
    
    public void SzczegolyWykluczeniaDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = SzczegolyWykluczenia.findSzczegolyWykluczeniaEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'SzczegolyWykluczenia' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<SzczegolyWykluczenia>();
        for (int i = 0; i < 10; i++) {
            SzczegolyWykluczenia obj = getNewTransientSzczegolyWykluczenia(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
