// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package pl.wroc.pwr.wiz.io.psi.model;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;
import pl.wroc.pwr.wiz.io.psi.model.Umowa;
import pl.wroc.pwr.wiz.io.psi.model.UmowaDataOnDemand;

privileged aspect UmowaDataOnDemand_Roo_DataOnDemand {
    
    declare @type: UmowaDataOnDemand: @Component;
    
    private Random UmowaDataOnDemand.rnd = new SecureRandom();
    
    private List<Umowa> UmowaDataOnDemand.data;
    
    public Umowa UmowaDataOnDemand.getNewTransientUmowa(int index) {
        Umowa obj = new Umowa();
        setLiczbaSztuk(obj, index);
        return obj;
    }
    
    public void UmowaDataOnDemand.setLiczbaSztuk(Umowa obj, int index) {
        int liczbaSztuk = index;
        obj.setLiczbaSztuk(liczbaSztuk);
    }
    
    public Umowa UmowaDataOnDemand.getSpecificUmowa(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Umowa obj = data.get(index);
        Long id = obj.getId();
        return Umowa.findUmowa(id);
    }
    
    public Umowa UmowaDataOnDemand.getRandomUmowa() {
        init();
        Umowa obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Umowa.findUmowa(id);
    }
    
    public boolean UmowaDataOnDemand.modifyUmowa(Umowa obj) {
        return false;
    }
    
    public void UmowaDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Umowa.findUmowaEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Umowa' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Umowa>();
        for (int i = 0; i < 10; i++) {
            Umowa obj = getNewTransientUmowa(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
