// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package pl.wroc.pwr.wiz.io.psi.model;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import pl.wroc.pwr.wiz.io.psi.model.AdresDataOnDemand;
import pl.wroc.pwr.wiz.io.psi.model.KontoFakturoweDataOnDemand;
import pl.wroc.pwr.wiz.io.psi.model.SposobAktywacji;
import pl.wroc.pwr.wiz.io.psi.model.StanKonta;
import pl.wroc.pwr.wiz.io.psi.model.Uzytkownik;
import pl.wroc.pwr.wiz.io.psi.model.UzytkownikDataOnDemand;
import pl.wroc.pwr.wiz.io.psi.model.WniosekRejestracyjny;
import pl.wroc.pwr.wiz.io.psi.model.WniosekRejestracyjnyDataOnDemand;
import pl.wroc.pwr.wiz.io.psi.service.dao.UzytkownikService;

privileged aspect UzytkownikDataOnDemand_Roo_DataOnDemand {
    
    declare @type: UzytkownikDataOnDemand: @Component;
    
    private Random UzytkownikDataOnDemand.rnd = new SecureRandom();
    
    private List<Uzytkownik> UzytkownikDataOnDemand.data;
    
    @Autowired
    AdresDataOnDemand UzytkownikDataOnDemand.adresDataOnDemand;
    
    @Autowired
    KontoFakturoweDataOnDemand UzytkownikDataOnDemand.kontoFakturoweDataOnDemand;
    
    @Autowired
    WniosekRejestracyjnyDataOnDemand UzytkownikDataOnDemand.wniosekRejestracyjnyDataOnDemand;
    
    @Autowired
    UzytkownikService UzytkownikDataOnDemand.uzytkownikService;
    
    public Uzytkownik UzytkownikDataOnDemand.getNewTransientUzytkownik(int index) {
        Uzytkownik obj = new Uzytkownik();
        setAkceptacjaZmianRegulaminu(obj, index);
        setCzyWykonalAkcje(obj, index);
        setDataOstatniegoLogowania(obj, index);
        setDataRozpoczeciaZamknieciaKonta(obj, index);
        setDataUrodzenia(obj, index);
        setDataUtworzenia(obj, index);
        setDataZamknieciaKonta(obj, index);
        setDrugiTelefon(obj, index);
        setEmail(obj, index);
        setFirma(obj, index);
        setHaslo(obj, index);
        setImie(obj, index);
        setKodAktywacyjny(obj, index);
        setLogin(obj, index);
        setNazwisko(obj, index);
        setOdKiedyZawieszone(obj, index);
        setPesel(obj, index);
        setPowodZamknieciaKonta(obj, index);
        setSposobAktywacji(obj, index);
        setStanKonta(obj, index);
        setTelefon(obj, index);
        setWniosekRejestracyjny(obj, index);
        setZamowioneZestawienieTransakcji(obj, index);
        return obj;
    }
    
    public void UzytkownikDataOnDemand.setAkceptacjaZmianRegulaminu(Uzytkownik obj, int index) {
        Date akceptacjaZmianRegulaminu = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setAkceptacjaZmianRegulaminu(akceptacjaZmianRegulaminu);
    }
    
    public void UzytkownikDataOnDemand.setCzyWykonalAkcje(Uzytkownik obj, int index) {
        Boolean czyWykonalAkcje = Boolean.TRUE;
        obj.setCzyWykonalAkcje(czyWykonalAkcje);
    }
    
    public void UzytkownikDataOnDemand.setDataOstatniegoLogowania(Uzytkownik obj, int index) {
        Date dataOstatniegoLogowania = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setDataOstatniegoLogowania(dataOstatniegoLogowania);
    }
    
    public void UzytkownikDataOnDemand.setDataRozpoczeciaZamknieciaKonta(Uzytkownik obj, int index) {
        Date dataRozpoczeciaZamknieciaKonta = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setDataRozpoczeciaZamknieciaKonta(dataRozpoczeciaZamknieciaKonta);
    }
    
    public void UzytkownikDataOnDemand.setDataUrodzenia(Uzytkownik obj, int index) {
        Date dataUrodzenia = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setDataUrodzenia(dataUrodzenia);
    }
    
    public void UzytkownikDataOnDemand.setDataUtworzenia(Uzytkownik obj, int index) {
        Date dataUtworzenia = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setDataUtworzenia(dataUtworzenia);
    }
    
    public void UzytkownikDataOnDemand.setDataZamknieciaKonta(Uzytkownik obj, int index) {
        Date dataZamknieciaKonta = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setDataZamknieciaKonta(dataZamknieciaKonta);
    }
    
    public void UzytkownikDataOnDemand.setDrugiTelefon(Uzytkownik obj, int index) {
        String drugiTelefon = "drugiTelefon_" + index;
        obj.setDrugiTelefon(drugiTelefon);
    }
    
    public void UzytkownikDataOnDemand.setEmail(Uzytkownik obj, int index) {
        String email = "foo" + index + "@bar.com";
        obj.setEmail(email);
    }
    
    public void UzytkownikDataOnDemand.setFirma(Uzytkownik obj, int index) {
        String firma = "firma_" + index;
        obj.setFirma(firma);
    }
    
    public void UzytkownikDataOnDemand.setHaslo(Uzytkownik obj, int index) {
        String haslo = "haslo_" + index;
        obj.setHaslo(haslo);
    }
    
    public void UzytkownikDataOnDemand.setImie(Uzytkownik obj, int index) {
        String imie = "imie_" + index;
        obj.setImie(imie);
    }
    
    public void UzytkownikDataOnDemand.setKodAktywacyjny(Uzytkownik obj, int index) {
        int kodAktywacyjny = index;
        obj.setKodAktywacyjny(kodAktywacyjny);
    }
    
    public void UzytkownikDataOnDemand.setLogin(Uzytkownik obj, int index) {
        String login = "login_" + index;
        obj.setLogin(login);
    }
    
    public void UzytkownikDataOnDemand.setNazwisko(Uzytkownik obj, int index) {
        String nazwisko = "nazwisko_" + index;
        obj.setNazwisko(nazwisko);
    }
    
    public void UzytkownikDataOnDemand.setOdKiedyZawieszone(Uzytkownik obj, int index) {
        Date odKiedyZawieszone = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setOdKiedyZawieszone(odKiedyZawieszone);
    }
    
    public void UzytkownikDataOnDemand.setPesel(Uzytkownik obj, int index) {
        String pesel = "pesel_" + index;
        obj.setPesel(pesel);
    }
    
    public void UzytkownikDataOnDemand.setPowodZamknieciaKonta(Uzytkownik obj, int index) {
        String powodZamknieciaKonta = "powodZamknieciaKonta_" + index;
        obj.setPowodZamknieciaKonta(powodZamknieciaKonta);
    }
    
    public void UzytkownikDataOnDemand.setSposobAktywacji(Uzytkownik obj, int index) {
        SposobAktywacji sposobAktywacji = SposobAktywacji.class.getEnumConstants()[0];
        obj.setSposobAktywacji(sposobAktywacji);
    }
    
    public void UzytkownikDataOnDemand.setStanKonta(Uzytkownik obj, int index) {
        StanKonta stanKonta = StanKonta.class.getEnumConstants()[0];
        obj.setStanKonta(stanKonta);
    }
    
    public void UzytkownikDataOnDemand.setTelefon(Uzytkownik obj, int index) {
        String telefon = "telefon_" + index;
        obj.setTelefon(telefon);
    }
    
    public void UzytkownikDataOnDemand.setWniosekRejestracyjny(Uzytkownik obj, int index) {
        WniosekRejestracyjny wniosekRejestracyjny = wniosekRejestracyjnyDataOnDemand.getRandomWniosekRejestracyjny();
        obj.setWniosekRejestracyjny(wniosekRejestracyjny);
    }
    
    public void UzytkownikDataOnDemand.setZamowioneZestawienieTransakcji(Uzytkownik obj, int index) {
        Boolean zamowioneZestawienieTransakcji = Boolean.TRUE;
        obj.setZamowioneZestawienieTransakcji(zamowioneZestawienieTransakcji);
    }
    
    public Uzytkownik UzytkownikDataOnDemand.getSpecificUzytkownik(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Uzytkownik obj = data.get(index);
        Long id = obj.getId();
        return uzytkownikService.findUzytkownik(id);
    }
    
    public Uzytkownik UzytkownikDataOnDemand.getRandomUzytkownik() {
        init();
        Uzytkownik obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return uzytkownikService.findUzytkownik(id);
    }
    
    public boolean UzytkownikDataOnDemand.modifyUzytkownik(Uzytkownik obj) {
        return false;
    }
    
    public void UzytkownikDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = uzytkownikService.findUzytkownikEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Uzytkownik' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Uzytkownik>();
        for (int i = 0; i < 10; i++) {
            Uzytkownik obj = getNewTransientUzytkownik(i);
            try {
                uzytkownikService.saveUzytkownik(obj);
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
