// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package pl.wroc.pwr.wiz.io.psi.model;

import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;
import pl.wroc.pwr.wiz.io.psi.model.WniosekRejestracyjnyDataOnDemand;
import pl.wroc.pwr.wiz.io.psi.model.WniosekRejestracyjnyIntegrationTest;
import pl.wroc.pwr.wiz.io.psi.service.dao.WniosekRejestracyjnyService;

privileged aspect WniosekRejestracyjnyIntegrationTest_Roo_IntegrationTest {
    
    declare @type: WniosekRejestracyjnyIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: WniosekRejestracyjnyIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: WniosekRejestracyjnyIntegrationTest: @Transactional;
    
    @Autowired
    WniosekRejestracyjnyDataOnDemand WniosekRejestracyjnyIntegrationTest.dod;
    
    @Autowired
    WniosekRejestracyjnyService WniosekRejestracyjnyIntegrationTest.wniosekRejestracyjnyService;
    
    @Test
    public void WniosekRejestracyjnyIntegrationTest.testCountAllWniosekRejestracyjnys() {
        Assert.assertNotNull("Data on demand for 'WniosekRejestracyjny' failed to initialize correctly", dod.getRandomWniosekRejestracyjny());
        long count = wniosekRejestracyjnyService.countAllWniosekRejestracyjnys();
        Assert.assertTrue("Counter for 'WniosekRejestracyjny' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void WniosekRejestracyjnyIntegrationTest.testFindWniosekRejestracyjny() {
        WniosekRejestracyjny obj = dod.getRandomWniosekRejestracyjny();
        Assert.assertNotNull("Data on demand for 'WniosekRejestracyjny' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'WniosekRejestracyjny' failed to provide an identifier", id);
        obj = wniosekRejestracyjnyService.findWniosekRejestracyjny(id);
        Assert.assertNotNull("Find method for 'WniosekRejestracyjny' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'WniosekRejestracyjny' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void WniosekRejestracyjnyIntegrationTest.testFindAllWniosekRejestracyjnys() {
        Assert.assertNotNull("Data on demand for 'WniosekRejestracyjny' failed to initialize correctly", dod.getRandomWniosekRejestracyjny());
        long count = wniosekRejestracyjnyService.countAllWniosekRejestracyjnys();
        Assert.assertTrue("Too expensive to perform a find all test for 'WniosekRejestracyjny', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<WniosekRejestracyjny> result = wniosekRejestracyjnyService.findAllWniosekRejestracyjnys();
        Assert.assertNotNull("Find all method for 'WniosekRejestracyjny' illegally returned null", result);
        Assert.assertTrue("Find all method for 'WniosekRejestracyjny' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void WniosekRejestracyjnyIntegrationTest.testFindWniosekRejestracyjnyEntries() {
        Assert.assertNotNull("Data on demand for 'WniosekRejestracyjny' failed to initialize correctly", dod.getRandomWniosekRejestracyjny());
        long count = wniosekRejestracyjnyService.countAllWniosekRejestracyjnys();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<WniosekRejestracyjny> result = wniosekRejestracyjnyService.findWniosekRejestracyjnyEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'WniosekRejestracyjny' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'WniosekRejestracyjny' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void WniosekRejestracyjnyIntegrationTest.testFlush() {
        WniosekRejestracyjny obj = dod.getRandomWniosekRejestracyjny();
        Assert.assertNotNull("Data on demand for 'WniosekRejestracyjny' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'WniosekRejestracyjny' failed to provide an identifier", id);
        obj = wniosekRejestracyjnyService.findWniosekRejestracyjny(id);
        Assert.assertNotNull("Find method for 'WniosekRejestracyjny' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyWniosekRejestracyjny(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'WniosekRejestracyjny' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void WniosekRejestracyjnyIntegrationTest.testUpdateWniosekRejestracyjnyUpdate() {
        WniosekRejestracyjny obj = dod.getRandomWniosekRejestracyjny();
        Assert.assertNotNull("Data on demand for 'WniosekRejestracyjny' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'WniosekRejestracyjny' failed to provide an identifier", id);
        obj = wniosekRejestracyjnyService.findWniosekRejestracyjny(id);
        boolean modified =  dod.modifyWniosekRejestracyjny(obj);
        Integer currentVersion = obj.getVersion();
        WniosekRejestracyjny merged = wniosekRejestracyjnyService.updateWniosekRejestracyjny(obj);
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'WniosekRejestracyjny' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void WniosekRejestracyjnyIntegrationTest.testSaveWniosekRejestracyjny() {
        Assert.assertNotNull("Data on demand for 'WniosekRejestracyjny' failed to initialize correctly", dod.getRandomWniosekRejestracyjny());
        WniosekRejestracyjny obj = dod.getNewTransientWniosekRejestracyjny(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'WniosekRejestracyjny' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'WniosekRejestracyjny' identifier to be null", obj.getId());
        try {
            wniosekRejestracyjnyService.saveWniosekRejestracyjny(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'WniosekRejestracyjny' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void WniosekRejestracyjnyIntegrationTest.testDeleteWniosekRejestracyjny() {
        WniosekRejestracyjny obj = dod.getRandomWniosekRejestracyjny();
        Assert.assertNotNull("Data on demand for 'WniosekRejestracyjny' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'WniosekRejestracyjny' failed to provide an identifier", id);
        obj = wniosekRejestracyjnyService.findWniosekRejestracyjny(id);
        wniosekRejestracyjnyService.deleteWniosekRejestracyjny(obj);
        obj.flush();
        Assert.assertNull("Failed to remove 'WniosekRejestracyjny' with identifier '" + id + "'", wniosekRejestracyjnyService.findWniosekRejestracyjny(id));
    }
    
}
