// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package pl.wroc.pwr.wiz.io.psi.model;

import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;
import pl.wroc.pwr.wiz.io.psi.model.Wojewodztwo;
import pl.wroc.pwr.wiz.io.psi.model.WojewodztwoDataOnDemand;
import pl.wroc.pwr.wiz.io.psi.model.WojewodztwoIntegrationTest;

privileged aspect WojewodztwoIntegrationTest_Roo_IntegrationTest {
    
    declare @type: WojewodztwoIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: WojewodztwoIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: WojewodztwoIntegrationTest: @Transactional;
    
    @Autowired
    WojewodztwoDataOnDemand WojewodztwoIntegrationTest.dod;
    
    @Test
    public void WojewodztwoIntegrationTest.testCountWojewodztwoes() {
        Assert.assertNotNull("Data on demand for 'Wojewodztwo' failed to initialize correctly", dod.getRandomWojewodztwo());
        long count = Wojewodztwo.countWojewodztwoes();
        Assert.assertTrue("Counter for 'Wojewodztwo' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void WojewodztwoIntegrationTest.testFindWojewodztwo() {
        Wojewodztwo obj = dod.getRandomWojewodztwo();
        Assert.assertNotNull("Data on demand for 'Wojewodztwo' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Wojewodztwo' failed to provide an identifier", id);
        obj = Wojewodztwo.findWojewodztwo(id);
        Assert.assertNotNull("Find method for 'Wojewodztwo' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Wojewodztwo' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void WojewodztwoIntegrationTest.testFindAllWojewodztwoes() {
        Assert.assertNotNull("Data on demand for 'Wojewodztwo' failed to initialize correctly", dod.getRandomWojewodztwo());
        long count = Wojewodztwo.countWojewodztwoes();
        Assert.assertTrue("Too expensive to perform a find all test for 'Wojewodztwo', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Wojewodztwo> result = Wojewodztwo.findAllWojewodztwoes();
        Assert.assertNotNull("Find all method for 'Wojewodztwo' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Wojewodztwo' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void WojewodztwoIntegrationTest.testFindWojewodztwoEntries() {
        Assert.assertNotNull("Data on demand for 'Wojewodztwo' failed to initialize correctly", dod.getRandomWojewodztwo());
        long count = Wojewodztwo.countWojewodztwoes();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Wojewodztwo> result = Wojewodztwo.findWojewodztwoEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Wojewodztwo' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Wojewodztwo' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void WojewodztwoIntegrationTest.testFlush() {
        Wojewodztwo obj = dod.getRandomWojewodztwo();
        Assert.assertNotNull("Data on demand for 'Wojewodztwo' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Wojewodztwo' failed to provide an identifier", id);
        obj = Wojewodztwo.findWojewodztwo(id);
        Assert.assertNotNull("Find method for 'Wojewodztwo' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyWojewodztwo(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Wojewodztwo' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void WojewodztwoIntegrationTest.testMergeUpdate() {
        Wojewodztwo obj = dod.getRandomWojewodztwo();
        Assert.assertNotNull("Data on demand for 'Wojewodztwo' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Wojewodztwo' failed to provide an identifier", id);
        obj = Wojewodztwo.findWojewodztwo(id);
        boolean modified =  dod.modifyWojewodztwo(obj);
        Integer currentVersion = obj.getVersion();
        Wojewodztwo merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Wojewodztwo' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void WojewodztwoIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Wojewodztwo' failed to initialize correctly", dod.getRandomWojewodztwo());
        Wojewodztwo obj = dod.getNewTransientWojewodztwo(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Wojewodztwo' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Wojewodztwo' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Wojewodztwo' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void WojewodztwoIntegrationTest.testRemove() {
        Wojewodztwo obj = dod.getRandomWojewodztwo();
        Assert.assertNotNull("Data on demand for 'Wojewodztwo' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Wojewodztwo' failed to provide an identifier", id);
        obj = Wojewodztwo.findWojewodztwo(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Wojewodztwo' with identifier '" + id + "'", Wojewodztwo.findWojewodztwo(id));
    }
    
}
