// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package pl.wroc.pwr.wiz.io.psi.model;

import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;
import pl.wroc.pwr.wiz.io.psi.model.ZawieszenieKontaDataOnDemand;
import pl.wroc.pwr.wiz.io.psi.model.ZawieszenieKontaIntegrationTest;
import pl.wroc.pwr.wiz.io.psi.service.dao.ZawieszenieKontaService;

privileged aspect ZawieszenieKontaIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ZawieszenieKontaIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ZawieszenieKontaIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: ZawieszenieKontaIntegrationTest: @Transactional;
    
    @Autowired
    ZawieszenieKontaDataOnDemand ZawieszenieKontaIntegrationTest.dod;
    
    @Autowired
    ZawieszenieKontaService ZawieszenieKontaIntegrationTest.zawieszenieKontaService;
    
    @Test
    public void ZawieszenieKontaIntegrationTest.testCountAllZawieszenieKontas() {
        Assert.assertNotNull("Data on demand for 'ZawieszenieKonta' failed to initialize correctly", dod.getRandomZawieszenieKonta());
        long count = zawieszenieKontaService.countAllZawieszenieKontas();
        Assert.assertTrue("Counter for 'ZawieszenieKonta' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ZawieszenieKontaIntegrationTest.testFindZawieszenieKonta() {
        ZawieszenieKonta obj = dod.getRandomZawieszenieKonta();
        Assert.assertNotNull("Data on demand for 'ZawieszenieKonta' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ZawieszenieKonta' failed to provide an identifier", id);
        obj = zawieszenieKontaService.findZawieszenieKonta(id);
        Assert.assertNotNull("Find method for 'ZawieszenieKonta' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'ZawieszenieKonta' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ZawieszenieKontaIntegrationTest.testFindAllZawieszenieKontas() {
        Assert.assertNotNull("Data on demand for 'ZawieszenieKonta' failed to initialize correctly", dod.getRandomZawieszenieKonta());
        long count = zawieszenieKontaService.countAllZawieszenieKontas();
        Assert.assertTrue("Too expensive to perform a find all test for 'ZawieszenieKonta', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<ZawieszenieKonta> result = zawieszenieKontaService.findAllZawieszenieKontas();
        Assert.assertNotNull("Find all method for 'ZawieszenieKonta' illegally returned null", result);
        Assert.assertTrue("Find all method for 'ZawieszenieKonta' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ZawieszenieKontaIntegrationTest.testFindZawieszenieKontaEntries() {
        Assert.assertNotNull("Data on demand for 'ZawieszenieKonta' failed to initialize correctly", dod.getRandomZawieszenieKonta());
        long count = zawieszenieKontaService.countAllZawieszenieKontas();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<ZawieszenieKonta> result = zawieszenieKontaService.findZawieszenieKontaEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'ZawieszenieKonta' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'ZawieszenieKonta' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ZawieszenieKontaIntegrationTest.testFlush() {
        ZawieszenieKonta obj = dod.getRandomZawieszenieKonta();
        Assert.assertNotNull("Data on demand for 'ZawieszenieKonta' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ZawieszenieKonta' failed to provide an identifier", id);
        obj = zawieszenieKontaService.findZawieszenieKonta(id);
        Assert.assertNotNull("Find method for 'ZawieszenieKonta' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyZawieszenieKonta(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'ZawieszenieKonta' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ZawieszenieKontaIntegrationTest.testUpdateZawieszenieKontaUpdate() {
        ZawieszenieKonta obj = dod.getRandomZawieszenieKonta();
        Assert.assertNotNull("Data on demand for 'ZawieszenieKonta' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ZawieszenieKonta' failed to provide an identifier", id);
        obj = zawieszenieKontaService.findZawieszenieKonta(id);
        boolean modified =  dod.modifyZawieszenieKonta(obj);
        Integer currentVersion = obj.getVersion();
        ZawieszenieKonta merged = zawieszenieKontaService.updateZawieszenieKonta(obj);
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'ZawieszenieKonta' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ZawieszenieKontaIntegrationTest.testSaveZawieszenieKonta() {
        Assert.assertNotNull("Data on demand for 'ZawieszenieKonta' failed to initialize correctly", dod.getRandomZawieszenieKonta());
        ZawieszenieKonta obj = dod.getNewTransientZawieszenieKonta(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'ZawieszenieKonta' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'ZawieszenieKonta' identifier to be null", obj.getId());
        try {
            zawieszenieKontaService.saveZawieszenieKonta(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'ZawieszenieKonta' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ZawieszenieKontaIntegrationTest.testDeleteZawieszenieKonta() {
        ZawieszenieKonta obj = dod.getRandomZawieszenieKonta();
        Assert.assertNotNull("Data on demand for 'ZawieszenieKonta' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ZawieszenieKonta' failed to provide an identifier", id);
        obj = zawieszenieKontaService.findZawieszenieKonta(id);
        zawieszenieKontaService.deleteZawieszenieKonta(obj);
        obj.flush();
        Assert.assertNull("Failed to remove 'ZawieszenieKonta' with identifier '" + id + "'", zawieszenieKontaService.findZawieszenieKonta(id));
    }
    
}
