// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package pl.wroc.pwr.wiz.io.psi.model;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import pl.wroc.pwr.wiz.io.psi.model.AukcjaDataOnDemand;
import pl.wroc.pwr.wiz.io.psi.model.Zdjecie;
import pl.wroc.pwr.wiz.io.psi.model.ZdjecieDataOnDemand;

privileged aspect ZdjecieDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ZdjecieDataOnDemand: @Component;
    
    private Random ZdjecieDataOnDemand.rnd = new SecureRandom();
    
    private List<Zdjecie> ZdjecieDataOnDemand.data;
    
    @Autowired
    AukcjaDataOnDemand ZdjecieDataOnDemand.aukcjaDataOnDemand;
    
    public Zdjecie ZdjecieDataOnDemand.getNewTransientZdjecie(int index) {
        Zdjecie obj = new Zdjecie();
        setOpis(obj, index);
        return obj;
    }
    
    public void ZdjecieDataOnDemand.setOpis(Zdjecie obj, int index) {
        String opis = "opis_" + index;
        obj.setOpis(opis);
    }
    
    public Zdjecie ZdjecieDataOnDemand.getSpecificZdjecie(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Zdjecie obj = data.get(index);
        Long id = obj.getId();
        return Zdjecie.findZdjecie(id);
    }
    
    public Zdjecie ZdjecieDataOnDemand.getRandomZdjecie() {
        init();
        Zdjecie obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Zdjecie.findZdjecie(id);
    }
    
    public boolean ZdjecieDataOnDemand.modifyZdjecie(Zdjecie obj) {
        return false;
    }
    
    public void ZdjecieDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Zdjecie.findZdjecieEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Zdjecie' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Zdjecie>();
        for (int i = 0; i < 10; i++) {
            Zdjecie obj = getNewTransientZdjecie(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
