// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package pl.wroc.pwr.wiz.io.psi.service.dao;

import java.util.List;
import pl.wroc.pwr.wiz.io.psi.model.WniosekZmianyImieniaINazwiska;
import pl.wroc.pwr.wiz.io.psi.service.dao.WniosekZmianyImieniaINazwiskaService;

privileged aspect WniosekZmianyImieniaINazwiskaService_Roo_Service {
    
    public abstract long WniosekZmianyImieniaINazwiskaService.countAllWniosekZmianyImieniaINazwiskas();    
    public abstract void WniosekZmianyImieniaINazwiskaService.deleteWniosekZmianyImieniaINazwiska(WniosekZmianyImieniaINazwiska wniosekZmianyImieniaINazwiska);    
    public abstract WniosekZmianyImieniaINazwiska WniosekZmianyImieniaINazwiskaService.findWniosekZmianyImieniaINazwiska(Long id);    
    public abstract List<WniosekZmianyImieniaINazwiska> WniosekZmianyImieniaINazwiskaService.findAllWniosekZmianyImieniaINazwiskas();    
    public abstract List<WniosekZmianyImieniaINazwiska> WniosekZmianyImieniaINazwiskaService.findWniosekZmianyImieniaINazwiskaEntries(int firstResult, int maxResults);    
    public abstract void WniosekZmianyImieniaINazwiskaService.saveWniosekZmianyImieniaINazwiska(WniosekZmianyImieniaINazwiska wniosekZmianyImieniaINazwiska);    
    public abstract WniosekZmianyImieniaINazwiska WniosekZmianyImieniaINazwiskaService.updateWniosekZmianyImieniaINazwiska(WniosekZmianyImieniaINazwiska wniosekZmianyImieniaINazwiska);    
}
